'use client';
import { ChangelogView, type ChangelogEntry } from '@/components/docs';

const CHANGELOG: ChangelogEntry[] = [
  // ─── v1.29.0 — AI surfaces promoted to @eidos/ui + stories + parity (2026-05-30) ──────
  { version: 'v1.29.0', date: '2026-05-30', type: 'feat', scope: 'ai', title: 'AI surfaces promoted to @eidos/ui exports + CSF3 stories',
    summary: 'The AI components (Tool, Reasoning, Plan, Context, History, Sources, ModelSelector, AskUser, AgentIdentity and the rest) are now first-class @eidos/ui exports with Storybook stories and registry items, restructured to the contract harness four-surface parity. API tables are generated from the typed props (<AutoPropsTable>), and the AI styling ships via the forge-ai registry item (ai.css). eidos add <component> now installs any AI surface component-by-component.' },

  // ─── v1.28.1 — Chat history routing per-thread + project tile destinations ──────
  { version: 'v1.28.1', date: '2026-05-28', type: 'fix', scope: 'examples', title: 'Chat history rows route per-thread — "breaker" goes to the Artifacts demo',
    summary: 'Every chat-history row in the sidebar (and every chat row inside a project detail / a search result) was hard-coded to /example/ai-chat-active?chat=<id>. The Artifacts surface (/example/ai-chat-artifacts) represents the "Draft a circuit breaker for bureau-gw" thread (id: breaker), but clicking that row from anywhere else opened the standard active-thread page, not the artifact view. Added chatHref(id: string): string in chat-shell.tsx with a CHAT_HREF_OVERRIDE map keyed by chat id — currently { breaker: \'/example/ai-chat-artifacts\' }; any chat NOT in the map falls back to the standard active-thread URL. The history sidebar (HistoryBucket), the project detail’s "Chats in this project" list, and the search results list all route through chatHref now, so the same thread always opens its canonical surface from any entry point.' },
  { version: 'v1.28.1', date: '2026-05-28', type: 'fix', scope: 'examples', title: 'AI · Projects — tile click routes to project detail with the right pinned id',
    summary: 'The Pix tribe tile on /example/ai-projects was routing to /example/ai-chat-active?chat=space-pix (a chat URL with a project id) and every other tile went to a default /example/ai-project-detail (no project context). Added an inline TILE_TO_PROJECT map ({ pix-tribe → space-pix, incident-library → space-incident, runbooks → space-runbook }) and route tile clicks to /example/ai-project-detail?project=<pinnedId> so the sidebar’s Pinned row highlights the matching project on arrival. Tiles without a pinned equivalent fall back to the default project context.' },

  // ─── v1.28.0 — AI Chat surface milestone (consolidation) ──────
  { version: 'v1.28.0', date: '2026-05-28', type: 'feat', scope: 'examples', title: 'AI Chat surface — 6 example pages, one shared shell, one ember CTA',
    summary: 'Milestone for the AI Chat experience. Six example surfaces now share a single chrome (FShell rail + a fixed 264px chat-history sidebar + the canonical PromptInput/PromptBanner composer), every row + chat is a real link, and the "Chat" rail icon is the entry point: /example/ai-chat (centred empty hero with radio-selectable starter chips), /example/ai-chat-active?chat=<id> (rich-markdown thread — chain of thought, response prose, table, blockquote, lists, citations, sources panel, SQL with hand-tokenised syntax, math, mermaid sequence diagram, CJK locales, code), /example/ai-projects (8 project tiles with stat footers), /example/ai-project-detail?project=<id> (folder header + Private pill + composer + files/instructions card + 5 chat rows), /example/ai-chat-search (focus-ringed search + recent chips + highlight-on-match results bucketed Today/This week/Earlier), /example/ai-chat-artifacts (chat ↔ docked ArtifactPanel that opens with the sidebar fading out and the chat narrowing in one fluid 280ms motion).' },
  { version: 'v1.28.0', date: '2026-05-28', type: 'fix', scope: 'message', title: 'Message — assistant reply is flat prose, user reply is a quoted chip',
    summary: 'Consolidates the conversational anatomy the v1.26.x patches landed: assistant .msg-bubble is transparent (no nested cards inside the bubble); user keeps the ember-soft bubble as the quoted prompt above the answer; assistant column is 92% of the stack vs the user’s 78%; the avatar lifts to align with the BOTTOM of the BUBBLE, not the bottom of the action toolbar, via :has() margin offsets per below-bubble row (.msg-actions, .msg-att-row, .msg-error-row); prose ordered + unordered lists share one marker → text gutter (12px) and one starting x (via a custom counter ::before for both, replacing the native ::marker on UL).' },
  { version: 'v1.28.0', date: '2026-05-28', type: 'feat', scope: 'prompt-input', title: 'Composer is the single source of truth across every chat surface',
    summary: 'All six chat examples render the same PromptInput from v1.24.x onwards: soft-ember submit at rest (ramps to solid on hover), top-banner ribbon authored via <PromptBanner tone="promo|info|warn|success|danger" cta? onDismiss?>, "+" actions menu replacing the paperclip, footer hint, optional elevated shadow, and the canonical DS Core focus ring. The promo banner CTA is always ember (DS-standard link color) regardless of tone — only the leading icon picks up the tone tint.' },

  // ─── v1.27.6 — AI Chat · Artifacts: open + close are both one fluid motion ──────
  { version: 'v1.27.6', date: '2026-05-28', type: 'fix', scope: 'examples', title: 'AI Chat · Artifacts — open AND close are both single fluid motions',
    summary: 'v1.27.5’s max-inline-size approach fixed close-from-frame-0 but introduced a new problem: the panel never fully collapsed (both chat and panel had flex-grow:1 in the closed state, so the panel kept ~180px even when "closed"), and opening got a snap too. Rebuilt the geometry around a SINGLE source of truth — a CSS variable --chat-w on .aica-shell that animates between 100% (panel closed) and 520px (panel open). The chat uses flex: 0 1 var(--chat-w) so its basis IS the variable; the panel uses flex: 1 1 0 and grows to claim whatever’s left over. With the Drawer’s own inline-size transition disabled (flex-basis: 0 wins over Drawer’s var(--dr-w)), the panel has no competing animation — its width is driven entirely by the chat’s flex-basis transitioning over 280ms cubic-bezier(0.32, 0.72, 0, 1). Verified by capturing widths at 0/80/160/240ms in both directions: chat + panel + sidebar all transition gradually together in BOTH directions, no snaps. One motion, end to end.' },

  // ─── v1.27.5 — AI Chat · Artifacts: close motion is one fluid step ──────
  { version: 'v1.27.5', date: '2026-05-28', type: 'fix', scope: 'examples', title: 'AI Chat · Artifacts — close animation is one fluid motion (was two steps)',
    summary: 'Closing the artifact panel snapped the chat to full width FIRST and then animated the panel closed — two visible steps. The chat constraint was on flex-basis (520px → auto on :has() match flipping), and the transition between a px value and "auto" can’t actually interpolate, so the chat jumped instantly. Switched the constraint to max-inline-size (animatable end to end: 520px ↔ 9999px) on a flex 1 1 auto column — the chat now glides between the two widths in lock-step with the Drawer’s 280ms inline-size animation. Also bumped the .cs-app grid transition from 240ms → 280ms with the same cubic-bezier so sidebar slide-in / artifact slide-out / chat width all land at the same instant.' },

  // ─── v1.27.4 — Prose: bullets and numbers share one alignment (2026-05-28) ──────
  { version: 'v1.27.4', date: '2026-05-28', type: 'fix', scope: 'prose', title: 'Prose lists — bullets follow the same custom marker pattern as numbers',
    summary: 'In a mixed-list response (some sections bulleted, others numbered) the bullets sat ~13px to the right of where the OL numbers started, because OL used a custom counter ::before (positioned at calc(100% + 12px) left of text) while UL still used the browser’s native ::marker. Switched UL to the same custom ::before pattern: list-style: none + position the • via inset-inline-end: calc(100% + 12px) + min-inline-size: 1.4em + text-align: end + a slightly larger glyph (1.15em) so the bullet reads at the same optical weight as the digits. Result: every list marker — bullet or number — starts at the same x and has the same 12px gutter to its text. Padding-inline-start unified to 32px for both list types.' },

  // ─── v1.27.3 — AI Chat · Artifacts: chat column 400 → 520 when panel open ──────
  { version: 'v1.27.3', date: '2026-05-28', type: 'fix', scope: 'examples', title: 'AI Chat · Artifacts — bumped the chat column to 520px when the artifact is open',
    summary: 'The mobile-width 400px chat column from v1.27.1 was a touch tight to read alongside the artifact panel — paragraphs broke onto too many short lines. Bumped to 520px so the chat is more comfortable as the lookup column while still leaving the artifact panel as the focal surface. The full-width fallback (panel closed) is unchanged.' },

  // ─── v1.27.2 — AI Chat · Artifacts: sidebar + chat width are responsive to panel state ──────
  { version: 'v1.27.2', date: '2026-05-28', type: 'feat', scope: 'examples', title: 'ChatShell — new sidebarCollapsed prop animates the chat history out of layout',
    summary: 'Added an optional sidebarCollapsed?: boolean prop to ChatShell. When true, the .cs-app grid-template-columns animates from 264px minmax(0, 1fr) → 0 minmax(0, 1fr) over 240ms (cubic-bezier(0.32, 0.72, 0, 1)), and the sidebar fades to opacity 0 + visibility hidden so it’s no longer in the focus order. Sidebar stays in the DOM — no remount, no scroll-position loss when it comes back. Used by the Artifacts example to give the focal surface (artifact panel + conversation) the full viewport width.' },
  { version: 'v1.27.2', date: '2026-05-28', type: 'fix', scope: 'examples', title: 'AI Chat · Artifacts — chat & sidebar widths track the artifact open state',
    summary: 'Bound the sidebarCollapsed prop to panelOpen: artifact open → sidebar collapsed; artifact closed → sidebar back. Then made the chat column responsive too: when the panel is open (matched via .aica-shell:has(.dr-root.variant-inline[data-state="open"])), .aica-chat is flex 0 0 400px (mobile-width column); when the panel is closed, .aica-chat expands to flex 1 1 auto with the inner .msg-thread capped at 820px for readability — so the chat reclaims its original full width instead of stranding empty space where the panel used to be. The .pi-shell composer max-width follows the same logic. Padding is tightened (24px → 18px inline) only while the panel is open so the bubbles don’t crowd the panel edge.' },

  // ─── v1.27.1 — AI Chat · Artifacts: chat mobile-width + panel grows + font parity ──────
  { version: 'v1.27.1', date: '2026-05-28', type: 'fix', scope: 'examples', title: 'AI Chat · Artifacts — chat column = mobile width, artifact panel grows',
    summary: 'The artifact-mode layout split the viewport roughly 50/50 between chat (flex 1) and a 520px artifact panel. When the user opens the runbook/document the artifact IS the focal surface — so the chat should shrink to a sidekick column and the panel should eat the rest. .aica-chat is now flex 0 0 400px (mobile-width column) and .aica-shell > .dr-root.variant-inline gets flex 1 1 auto + inline-size: auto (overriding Drawer’s default fixed inline-size: var(--dr-w)), so the panel takes whatever horizontal space is left. The width prop on <ArtifactPanel/> now acts as the MIN width via min-inline-size so the panel never collapses below 520px on narrow viewports. Below 1080px the existing media query still stacks the two vertically.' },
  { version: 'v1.27.1', date: '2026-05-28', type: 'fix', scope: 'examples', title: 'AI Chat · Artifacts — prose font matches the main chat',
    summary: 'The runbook inside <ArtifactPanel/> rendered at .ai-prose’s default 15px / 1.65, which read visibly larger than the conversation beside it (the main chat sits in .msg-bubble territory at 13.5px / 1.6). Scoped override on .aica-shell .dr-body .ai-prose normalizes the artifact body to 13.5px / 1.6 (with h2 19px and h3 15px) so the artifact and the chat feel like one document at one scale, not two voices at different volumes. Override is local to this example — other surfaces using ArtifactPanel keep the default prose size.' },

  // ─── v1.27.0 — AI · Project detail rebuilt + Pinned routing (2026-05-28) ──────
  { version: 'v1.27.0', date: '2026-05-28', type: 'feat', scope: 'examples', title: 'AI · Project detail — rebuilt with the new chat components',
    summary: 'The old ai-project-detail surface used the legacy AIShell + AIPromptInput, which didn’t match the rest of the chat experience and rendered out of alignment. Rebuilt from scratch on ChatShell with the same components every other chat page uses: PromptInput + PromptBanner for the composer, the canonical sidebar, the new icon set. The page is now: back link → header (folder tile + name + Private pill + star + ⋯) → composer with promo banner → two-column card (Project files: colour-coded XLS/DOC/PDF/CSV chips + dashed "+" add button · Instructions: 3-line clamp + edit pencil) → "Chats in this project" list with 5 chat rows that link to ai-chat-active?chat=<id>. Layout glue is page-local; every colour/radius/spacing comes from DS tokens. Reads ?project=<id> from the URL so a refresh keeps the project context.' },
  { version: 'v1.27.0', date: '2026-05-28', type: 'fix', scope: 'examples', title: 'ChatShell — Pinned projects route to ai-project-detail',
    summary: 'The Pinned spaces in the chat sidebar (Pix tribe, Incident library, Runbooks) were routing to /example/ai-chat-active?chat=<id>, which was the chat-thread surface — wrong for a project click. They now route to /example/ai-project-detail?project=<id>. activeChat continues to match (the active row stays ember-highlighted) since pinned ids are stable across both pages.' },
  { version: 'v1.27.0', date: '2026-05-28', type: 'feat', scope: 'icons', title: 'icons.tsx — new "lock" glyph for Private badges',
    summary: 'Added Icons.lock (padlock body + curved shackle) so the Private badge on the project detail page can use a semantic glyph instead of repurposing Icons.shield. Generic enough for any "this is private / sealed" UI affordance.' },

  // ─── v1.26.5 — AI Chat search: hide native input clear (2026-05-28) ──────
  { version: 'v1.26.5', date: '2026-05-28', type: 'fix', scope: 'examples', title: 'AI Chat · Search — hide the browser’s native search-input × ',
    summary: 'The big search field in /example/ai-chat-search was rendering TWO clear buttons: our themed .clear × (ember tinted, fires onClick={() => setQ("")}) and the browser’s built-in <input type="search"> clear ×. The native one is appended to the end of the input box on WebKit / Blink (Chrome, Safari, Edge) which made the trailing edge read as ×× esc. Added input::-webkit-search-cancel-button + input::-webkit-search-decoration with -webkit-appearance: none + display: none so only our themed × remains. Firefox doesn’t render a native clear on type="search" so no extra rule needed there.' },

  // ─── v1.26.4 — AI Chat empty: suggestion chips wired (radio) ──────
  { version: 'v1.26.4', date: '2026-05-28', type: 'feat', scope: 'examples', title: 'AI Chat (empty) — suggestion chips behave as a radio group + populate composer',
    summary: 'Clicking a starter chip now: (a) sets its label as the composer text (with a trailing space so the user can keep typing nuance) and (b) highlights the chip with the ember-soft is-on state via the existing pressed prop on <Suggestion/>. Selection is DERIVED from text.startsWith(label), so only one chip can be highlighted at a time (radio-style: picking another chip clears the previous highlight automatically), and editing the prompt past the starter or clearing it deselects the chip on its own — no extra state to keep in sync. Clicking the SAME chip again toggles off (clears the composer).' },

  // ─── v1.26.3 — AI Chat empty: one centred group (2026-05-28) ──────
  { version: 'v1.26.3', date: '2026-05-28', type: 'fix', scope: 'examples', title: 'AI Chat (empty) — hero + chips + composer as one vertically-centred group',
    summary: 'The empty new-chat surface was a 3-row grid (1fr · auto · auto): the hero floated mid-page, the suggestion chips + composer were pinned to the bottom, leaving a big visual gap between greeting and prompt. It now uses flex column + justify-content: center so the WHOLE group (ForgeMark → "Hello, Leonardo" → supporting text → 4 suggestion chips → composer with the promo banner → footer hint) sits as a single block at the vertical centre of the main area. The 18px gap keeps them close enough to read as one piece while the composer remains the obvious tap target. Matches the requested reference visual.' },

  // ─── v1.26.2 — Prose: wider assistant width, OL gutter, SQL syntax demo (2026-05-28) ──────
  { version: 'v1.26.2', date: '2026-05-28', type: 'fix', scope: 'message', title: 'Assistant message — wider stack (92% vs 78%)',
    summary: 'Assistant replies were capped at the same 78% stack width as user bubbles, which squeezed long-form content (tables, code, equations, multi-locale lists). Since the assistant side has no bubble (v1.26.1), it can comfortably use more of the column without competing with the user prompt. .msg.assistant .msg-stack is now max-width: 92%; user stays at 78% so its bubble keeps reading as a quoted prompt above the answer.' },
  { version: 'v1.26.2', date: '2026-05-28', type: 'fix', scope: 'prose', title: 'Ordered list — wider gutter between marker and text',
    summary: 'The default list-style rendered "1." too close to the first word, especially when the word was bold (the eye couldn’t separate marker from content). .ai-prose ol now uses a custom counter (counter-reset / counter-increment + ::before) with explicit positioning: marker sits 12px LEFT of the text (inset-inline-end: calc(100% + 12px)) with tabular-nums so two-digit numbers align with single-digit ones. Padding-inline-start bumped from 22px → 32px to make room. Bullet lists (ul) keep the native ::marker since the bullet vs text gap was already legible.' },
  { version: 'v1.26.2', date: '2026-05-28', type: 'feat', scope: 'prose', title: 'Prose — token classes for hand-tokenised syntax highlighting',
    summary: 'Added 8 token-colour classes to .ai-code-body for hand-tokenised code samples: .tok-key (ember keywords), .tok-str (success-green strings), .tok-num (info-blue numbers), .tok-com (muted italic comments), .tok-fn (info-blue function names), .tok-typ (purple types), .tok-op (muted operators), .tok-var (default fg). The DS still does NOT bundle Shiki / Prism — these are demo-grade roles a consumer can wrap around tokens; production should use a build-time highlighter. The Active thread example now wraps a SQL validation-queries snippet in these tokens so the docs surface what real syntax highlighting looks like.' },
  { version: 'v1.26.2', date: '2026-05-28', type: 'docs', scope: 'examples', title: 'AI Chat · Active thread — SQL validation block with syntax highlighting',
    summary: 'Added a SQL block (Validation queries) to the rich-features answer in /example/ai-chat-active. It uses a small inline HighlightedCode helper that renders the .ai-code shell but accepts pre-tokenised children (via local K/S/N/C/F/T span helpers) and a separate `raw` plain-text source for the Copy button. The result: a SELECT…FROM…WHERE block with ember keywords, blue function names, green string literals, italic muted comments. Pairs with the existing bash code block so the example now demos two languages.' },

  // ─── v1.26.1 — AI Chat: 5 fixes (scroll, CTA, bubble, avatar, rich content) (2026-05-28) ──────
  { version: 'v1.26.1', date: '2026-05-28', type: 'fix', scope: 'examples', title: 'ChatShell — sidebar + main scroll independently',
    summary: 'The chat shell was using min-block-size on .cs-app, so both columns shared the page-level scroll. Switched to a fixed block-size: calc(100dvh - 48px) on .cs-app plus overflow-y: auto + min-block-size: 0 + block-size: 100% on both .cs-side and .cs-main. The sidebar now stays put while the conversation scrolls — the standard chat pattern.' },
  { version: 'v1.26.1', date: '2026-05-28', type: 'fix', scope: 'examples', title: 'ChatShell — "New chat" CTA is always ember (consistent across pages)',
    summary: 'The CTA was filled ember only on /ai-chat and a ghost-outlined variant on every other chat page (Projects, Search, Active thread, Artifacts). That made it harder to find consistently. The "you are in chat" cue belongs to the Chat-icon highlight in the rail; the CTA always means "start a new thread". So the .cs-newchat:not(.is-active) override was deleted — the button is now primary ember on every chat surface.' },
  { version: 'v1.26.1', date: '2026-05-28', type: 'fix', scope: 'message', title: 'Assistant Message — bubble dropped, reply reads as flat prose',
    summary: 'Assistant replies were wrapped in the same bordered surface as user messages, which made long answers look like nested cards inside another card (especially with ChainOfThought and Response composed inside). Updated .msg.assistant .msg-bubble to background: transparent + border: 0 + padding: 0 + border-radius: 0. The user side keeps its ember-soft bubble — it reads as a quoted prompt above the answer. Pre/code blocks inside an assistant reply got an explicit --bg-elevated background so they still contrast against the flat surface. Matches the modern chat pattern (Claude, ChatGPT).' },
  { version: 'v1.26.1', date: '2026-05-28', type: 'fix', scope: 'message', title: 'Message — avatar aligns with bubble bottom, not the action toolbar',
    summary: 'With align-items: flex-end on .msg, the assistant avatar dropped to the bottom of the .msg-stack (which includes the actions toolbar below the bubble). It now lifts by exactly the rows below the bubble: 32px when actions are present, 12px for the attachment row, 24px for the error row — using :has() so the rule is markup-free. Effect: the avatar sits next to the last visible line of the BUBBLE, where the eye expects it, even when actions are visible.' },
  { version: 'v1.26.1', date: '2026-05-28', type: 'fix', scope: 'examples', title: 'AI Chat · Active thread — rich-features answer replaces the streaming demo',
    summary: 'The active-thread example ended on a streaming "writing…" turn, which doubled the streaming docs from the Streaming page. Replaced it with a finalized rich-features answer (the "answer ready" canonical state). The new turn exercises: a block + inline MathView for the p99 win equation, an inline-SVG sequence diagram via Diagram, the comparison table (kept), a CJK-localised rollback summary (EN · PT-BR · 日本語 · 简体中文 with per-li lang attributes), and a ProseCode block. Composer status flipped from streaming to ready. Streaming behaviour is still documented on the dedicated Streaming page.' },

  // ─── v1.26.0 — AI Chat surface: 5 examples, Chat rail, ChatShell (2026-05-28) ──────
  { version: 'v1.26.0', date: '2026-05-28', type: 'feat', scope: 'examples', title: 'AI Chat surface — 5 separate example pages with real navigation',
    summary: 'The AI chat experience now spans 5 example pages, each a real route with real links between them: /example/ai-chat (empty hero + composer), /example/ai-chat-active?chat=<id> (rich thread with chain of thought, Response/Prose markdown, table, blockquote, lists, code, Citations + Sources, streaming follow-up), /example/ai-projects (8-tile project grid with stats), /example/ai-chat-search (focus-ringed search field with highlight-on-match results grouped Today/This week/Earlier), and /example/ai-chat-artifacts (docked ArtifactPanel beside the conversation showing a runbook). All five share the new ChatShell helper — FShell rail + a 264px chat-history sidebar (using the canonical .ai-hist-* visuals but with <a> rows so clicking actually navigates) + the page content as children. Project ids in the sidebar route to the active-thread page with ?chat=<id>; "Projects", "Search chats", and "New chat" route between the surfaces. The "Chat" rail icon (new) is the entry point.' },
  { version: 'v1.26.0', date: '2026-05-28', type: 'feat', scope: 'examples', title: 'FShell rail — new "Chat" item beside Home',
    summary: 'Added a Chat icon (speech-bubble, new in icons.tsx) to the FShell RAIL pointing at /example/ai-chat. The rail item is highlighted as active on every chat page (the ChatShell wrapper passes nav="chat" through to FShell). This makes the chat surface a first-class destination in the product chrome, separate from the Agents page (which lists individual agents).' },
  { version: 'v1.26.0', date: '2026-05-28', type: 'fix', scope: 'examples', title: 'ai-projects — header, search, tile grid + ChatShell migration',
    summary: 'Refreshed the existing AI Projects example to use ChatShell (same chat sidebar everywhere) and reworked the card grid: 8 project tiles (was 6) with auto-fill minmax(280px, 1fr) so tiles always sit on clean rows at any width, an icon tile + name + description + a 3-stat mono footer (chats · docs · updated), a proper page header (eyebrow + title + lede + "Create project" ember CTA), and a search-on-leading-edge / sort-on-trailing-edge toolbar. Empty state when search returns nothing.' },

  // ─── v1.25.0 — AI Chat flagship example (2026-05-28) ──────
  { version: 'v1.25.0', date: '2026-05-28', type: 'feat', scope: 'examples', title: 'AI Chat — flagship example with both empty + active thread views',
    summary: 'New example at /example/ai-chat showcases the FULL chat surface using only canonical AI primitives — proper AISidebar (Projects / Library / Pinned / Recents / Yesterday + user pill with theme toggle), AITopbar, and the new v1.24.x <PromptInput/> + <PromptBanner/>. A small segmented control in the topRight slot swaps between two views: "New chat" (centred ForgeMark hero + 4 suggestion chips + a promo-banner-equipped composer with footer hint) and "Active thread" (a rich Postgres-migration conversation that exercises Chain of Thought, a Response with H3/H4 headings, paragraph + inline Citations [1][2], comparison table, blockquote, ordered + unordered lists, inline code, a copy-able code block, MessageActions toolbar, a Sources panel, and a streaming assistant follow-up). The composer is docked at the bottom with a soft fade and shows the "streaming → stop" state. Old examples (ai-chat-empty, ai-chat-thread) stay published as "AI · New chat" / "AI · Chat thread" for backward compat — the new ai-chat supersedes them in the sidebar.' },

  // ─── v1.24.3 — PromptBanner CTA: always ember (DS-standard link colour) (2026-05-28) ──────
  { version: 'v1.24.3', date: '2026-05-28', type: 'fix', scope: 'prompt-input', title: 'PromptBanner CTA — always ember, never re-tinted per tone',
    summary: 'The warn-tone CTA was painting amber and the danger-tone CTA was painting red — same as the icon. That broke the DS rule that link/action affordances use the single ember accent so users learn one cue. The CTA now stays var(--ember) across all five tones (promo / info / success / warn / danger); tone still tints the leading icon so the message intent reads at a glance, but every "Upgrade →" / "Switch model" / "Retry" looks the same colour you click. Also stays within the 2× ember-per-screen budget since the icon never gets ember on non-promo tones.' },

  // ─── v1.24.2 — PromptBanner: 5 tones, dismissible, banner layout polish (2026-05-28) ──────
  { version: 'v1.24.2', date: '2026-05-28', type: 'feat', scope: 'prompt-input', title: 'PromptBanner — new sub-component with 5 tones + dismissible × ',
    summary: 'The topBanner slot now has a canonical sub-component <PromptBanner/>. Five tones (promo · info · success · warn · danger) tint only the leading icon and the trailing CTA — the banner background stays transparent so it shares the shell surface with the input field. Optional cta + onCtaClick render an ember-tinted text button at the trailing edge; optional onDismiss renders a × button after the CTA (the caller owns the visible state, typically a React state + localStorage key so dismissals stick). Defaults to "promo" (ember sparkle + ember CTA) matching the original v1.24.0 demo. Each tone picks a sensible default icon (sparkle / info / check / alert / alert) which can be overridden via icon="…".' },
  { version: 'v1.24.2', date: '2026-05-28', type: 'fix', scope: 'prompt-input', title: 'Banner layout — focus ring wraps the whole component, only top edge rounding visible',
    summary: 'Walked back v1.24.1’s outer ribbon / nested rounded card with its own focus ring (which moved the ring to the inner field and added a padded gap). The composer is now: outer .pi keeps its single rounded border + focus ring (so the ring wraps banner + input together — including the banner), .pi paints --bg-elevated as a softer backdrop, banner sits flush at the top with a transparent bg, the nested .pi-field has only the TOP-CORNER border-radius (sides + bottom flush against the .pi border). The visual contract: only the input area’s TOP edge shows the rounded transition; sides and bottom are married with the outer container — matching the reference image exactly.' },
  { version: 'v1.24.2', date: '2026-05-28', type: 'docs', scope: 'prompt-input', title: 'Prompt Input page — Banner tones gallery + Dismissible demos',
    summary: 'Two new sections: Banner tones — five composers stacked vertically, one per tone (promo / info / success / warn / danger), each with a tone-appropriate message and CTA; Dismissible — a single info banner with the × handler wired to React state plus a "Restore banner" button so the dismissed-then-shown round-trip is demonstrable. The original Top banner section now shows the simple no-CTA info ribbon. The Enhanced composer demo and EnhancedCode snippet were migrated to use <PromptBanner/>. API reference grew a separate <PromptBanner /> props table.' },

  // ─── v1.24.1 — PromptInput banner: nested rounded input card (2026-05-28) ──────
  { version: 'v1.24.1', date: '2026-05-28', type: 'fix', scope: 'prompt-input', title: 'PromptInput with topBanner — input area gets its own rounded card',
    summary: 'Previously, when topBanner was set, the banner sat inside the same single rounded shell as the textarea + footer, separated only by a hairline. The input field had no rounded TOP corners of its own — it was flush against the banner divider. The shell now switches into a soft outer ribbon (bg-elevated, 6px padding, .pi.has-banner modifier) holding the banner ABOVE a NESTED rounded card (.pi-field, 10px radius, surface bg, all four corners rounded) that owns the body + footer. The focus ring moved from the outer .pi to .pi-field — so it surrounds only the actual input area, not the banner — matching the reference image. Without a banner, .pi keeps its original single-rounded-card look (no behavioural change).' },

  // ─── v1.24.0 — PromptInput enhanced: banner, + actions, hint, elevated, soft submit (2026-05-28) ──────
  { version: 'v1.24.0', date: '2026-05-28', type: 'feat', scope: 'prompt-input', title: 'PromptInput — topBanner ribbon inside the field',
    summary: 'New topBanner?: ReactNode prop renders a hairline-bordered ribbon ABOVE the textarea, INSIDE the bordered shell. Defaults to mono caption sizing with a muted bg-elevated background. Two helper classes — .pi-banner-icon for a leading 16px glyph slot, and .pi-banner-cta for an ember-tinted trailing CTA — keep ribbon contents consistent across products. Use for upgrade prompts ("Access premium models & features · Upgrade"), beta tags, region notices.' },
  { version: 'v1.24.0', date: '2026-05-28', type: 'feat', scope: 'prompt-input', title: 'PromptInput — "+" actions menu replaces the paperclip',
    summary: 'New actions?: PromptInputAction[] and onActionSelect?: (id) => void props. When set, the default paperclip button is replaced by a "+" trigger that opens a portaled context menu. Each item supports id, label, optional icon (any Icons.* name), optional description (second line, muted), divider:true for hairline separators, and destructive:true for danger-tinted rows. Same portal + position pattern as ModelSelector — the menu escapes any container clipping and flips above/below the trigger based on viewport room. Typical menu: Upload images or files · Generate image · Deep search · (divider) · Clear conversation (destructive).' },
  { version: 'v1.24.0', date: '2026-05-28', type: 'feat', scope: 'prompt-input', title: 'PromptInput — footerHint and elevated props',
    summary: 'Two more optional slots: footerHint?: ReactNode renders supporting text BELOW the bordered shell — small, muted, centred — for legal nags like "AI can make mistakes — please double-check important answers." elevated?: boolean adds the subtlest DS shadow (--shadow-1) below the field for a soft lift. Both compose freely with topBanner and actions; turn on only the slots you need.' },
  { version: 'v1.24.0', date: '2026-05-28', type: 'fix', scope: 'prompt-input', title: 'PromptInput submit — soft ember at rest, not the loud solid fill',
    summary: 'The submit button was a solid ember fill at rest, which made every PromptInput in the docs read as marketing chrome. It now uses the soft ember tint (ember-soft background + ember glyph + ember-22%-mix border) at rest, ramping to solid ember + ember-fg on hover — the same accent ramp pattern used elsewhere in Core. The "send" affordance still owns the accent in the active moment without burning the ember budget the rest of the time. Error variant got the same ramp (danger-soft → solid danger on hover); streaming/submitted variants are unchanged.' },
  { version: 'v1.24.0', date: '2026-05-28', type: 'fix', scope: 'prompt-input', title: 'PromptInput focus ring — switched to the canonical DS Core ring tokens',
    summary: 'The .pi:focus-within ring was using the surface-input box-shadow glow pattern (3px ember-soft halo + ember border), which is fine for inline controls (ds-topbar-search etc.) but the composer is a primary input. It now uses the documented DS Core convention: outline: var(--ring-width) solid var(--ring); outline-offset: var(--ring-offset); — the same 2px ember outline with 2px offset gap used by .focus-ring, .btn, .fc-*, .in-*. Invalid variant flips outline-color to var(--ring-danger).' },
  { version: 'v1.24.0', date: '2026-05-28', type: 'docs', scope: 'prompt-input', title: 'Prompt Input page — Enhanced composer, Top banner, Actions menu sections',
    summary: 'Three new component sections between Full toolbar and Attachments: Enhanced composer (all four slots wired, with a soft submit + soft drop-shadow demo), Top banner (ribbon-only minimal example), Actions menu (+ menu with 3 sample actions + live "picked id" feedback in the hint). API reference grew the topBanner / actions / onActionSelect / footerHint / elevated / contextSlot rows and a separate PromptInputAction table.' },

  // ─── v1.23.1 — Conversation small polish (2026-05-28) ──────
  { version: 'v1.23.1', date: '2026-05-28', type: 'fix', scope: 'conversation', title: 'Jump-pill bare button — icon centred',
    summary: 'The bare-arrow variant of the jump-to-latest button was rendering the icon at the leading edge instead of the centre. The base .conv-jump uses inline-flex without justify-content; the bare variant now sets justify-content: center so the chevron-down sits perfectly in the middle of the 32×32 round button.' },
  { version: 'v1.23.1', date: '2026-05-28', type: 'fix', scope: 'conversation', title: 'Spacing tokens table — horizontal scroll on overflow',
    summary: 'The spacing tokens table was breaking the page layout when narrower than its 3 columns. Wrapped the surface in overflow-x: auto and pinned the table at min-width: 720px so it scrolls horizontally instead of pushing the column outside the section.' },
  { version: 'v1.23.1', date: '2026-05-28', type: 'docs', scope: 'conversation', title: 'conv-foot — fade-out into the prompt input, like the code-block "Show code"',
    summary: 'The footer that hosts the suggestions row + prompt input previously had a bg-elevated background with a hard border-top, which read as a strong divider between the chat and the input. It now uses var(--bg) (the SAME background as the chat) with no border, and a gradient ::before above (40px tall, from var(--bg) to transparent) so the last messages dissolve INTO the foot — the same fade pattern the code-block surface uses before its "Show code" pill, giving the input the feel of an iOS toolbar with the chat continuing behind it.' },

  // ─── v1.23.0 — Conversation polish: ForgeMark, burst, jump-pill, full chat (2026-05-28) ──────
  { version: 'v1.23.0', date: '2026-05-28', type: 'feat', scope: 'conversation', title: 'Burst pattern — same-speaker follow-ups collapse meta + avatar',
    summary: 'When the same speaker sends consecutive messages, the meta row (name + time + model) now only appears above the FIRST message of the burst, and the avatar only beside the LAST one — aligned to the bottom of that bubble (.msg has align-items: flex-end). Achieved via :has(+ .msg.same-speaker) and adjacent-sibling selectors — consumers don’t need to mark anything. Visibility:hidden on non-last avatars preserves the horizontal layout so bubbles stay aligned.' },
  { version: 'v1.23.0', date: '2026-05-28', type: 'fix', scope: 'conversation', title: 'Equal-rounded bubbles — dropped the 4px corner tail',
    summary: 'Both user and assistant bubbles previously had an asymmetric "tail" corner (border-end-end-radius: 4px on user, border-end-start-radius: 4px on assistant). The 4px cut was barely visible and read inconsistent — bubbles now have equal 12px on all corners. (The fluidfunctionalism-style iMessage tail would require a pseudo-element + background-mask which doesn’t survive arbitrary chat container backgrounds; equal rounding was the pragmatic call.)' },
  { version: 'v1.23.0', date: '2026-05-28', type: 'feat', scope: 'conversation', title: 'Jump-pill stays visible whenever the user is scrolled up',
    summary: 'Previously the jump-to-latest pill only appeared when there were unread messages. It now also appears as a small bare arrow button when the user is simply scrolled away from the bottom (no unread), so navigating back to live is always one click away. The pill variant with the unread count is still shown when there are new messages.' },
  { version: 'v1.23.0', date: '2026-05-28', type: 'docs', scope: 'conversation', title: 'ForgeMark logo replaces the flame icon in every conv header',
    summary: 'Every Conversation header demo now uses the canonical <ForgeMark/> brand mark (the sparkle-around-flame composition exported from icons.tsx) instead of <Icons.flame/>. Consistent with the favicon and the brand identity.' },
  { version: 'v1.23.0', date: '2026-05-28', type: 'feat', scope: 'conversation', title: 'Full chat surface — PromptInput docked inside the conv container',
    summary: 'The Full chat surface demo previously rendered the prompt input as a hand-rolled textarea floating below the conv container. It now uses the real <PromptInput/> + a Suggestions row, both docked inside a new .conv-foot block (border-top, bg-elevated). The PromptInput max-width is unlocked inside the foot so it fills the row. Demo height bumped to 720px for room to breathe.' },
  { version: 'v1.23.0', date: '2026-05-28', type: 'docs', scope: 'conversation', title: 'Document mode — bg-elevated background, longer demo, dropped bubble tail',
    summary: 'Document mode now uses --bg-elevated as its background so the document reads as its own surface against the page; the user bubble dropped its 4px tail to match the messages rule; and the demo got a second user/assistant turn (rollback plan with validation list + blockquote) so the multi-block prose-scale answer pattern is fully visible.' },

  // ─── v1.22.0 — AI chat spacing scale (2026-05-28) ──────
  { version: 'v1.22.0', date: '2026-05-28', type: 'tokens', scope: 'message', title: 'AI chat spacing — a real scale, five tokens',
    summary: 'Both .msg-thread and .conv-body now share five CSS custom-property tokens that hosts can override: --ai-thread-pad-block / --ai-thread-pad-inline (24/24 — keeps avatars off container edges, including the docked artifact drawer), --ai-turn-gap (24 — between different speakers), --ai-turn-gap-follow (6 — between same-speaker follow-ups so a "burst" reads tight), and --ai-avatar-gap (12 — between avatar and bubble). Burst detection is automatic via adjacent-sibling selectors (.msg.user + .msg.user, etc.); consumers don’t need to set a class.' },
  { version: 'v1.22.0', date: '2026-05-28', type: 'fix', scope: 'artifact', title: 'Artifact demos — chat column wraps in .msg-thread',
    summary: 'The Artifact page’s Usage and Kinds demos previously laid messages in a raw flex column with arbitrary padding, which is why the user avatar appeared glued to the docked drawer edge. They now wrap in .msg-thread.fluid and inherit the canonical spacing tokens — 24px inset from the drawer, 24px between turns, 6px between same-speaker follow-ups.' },
  { version: 'v1.22.0', date: '2026-05-28', type: 'docs', scope: 'conversation', title: 'Spacing scale documented on the Conversation page',
    summary: 'New Spacing scale section (with a live demo showing turn-change vs follow-up gap) + a tokens table listing every spacing custom property and what it controls. Two constants are explicitly NOT tokenised — bubble corner radius (12px with a 4px tail) and bubble max-width (78%) — because they shouldn’t vary across surfaces.' },

  // ─── v1.21.0 — Drawer in Core · richer AudioPlayer · Terminal icon (2026-05-28) ──────
  { version: 'v1.21.0', date: '2026-05-28', type: 'feat', scope: 'ai', title: 'Drawer promoted to Core + inline variant for docked artifacts',
    summary: 'The Drawer (previously inline in migrated/drawer.tsx) is now a real Core primitive at src/ds/core/drawer.tsx. A new variant prop adds an "inline" mode: instead of overlaying as a portal with a backdrop, the drawer participates in the parent layout — animating its inline-size from 0 → width — so siblings (like a chat column) shrink to make room when it opens and reclaim the space on close. ArtifactPanel was refactored to compose Drawer in inline mode, keeping its tabs / actions / kind-aware body rendering (document via react-markdown into Prose, code via ProseCode, html via sanitised dangerouslySetInnerHTML).' },
  { version: 'v1.21.0', date: '2026-05-28', type: 'feat', scope: 'audio-player', title: 'AudioPlayer — richer controls (skip ±10s, speed pill, cover, peaks waveform)',
    summary: 'AudioPlayer was reshaped to match the elements.ai-sdk.dev pattern: skip-back / play / skip-forward triplet (▲ ▶ ▼ icons added to icons.tsx), a speed pill that cycles through 0.75× / 1× / 1.25× / 1.5× / 2×, optional cover artwork slot, optional subtitle line, and an optional peaks array that renders a real waveform (played portion tints ember, tail stays neutral). The scrubber is now click-to-seek with ← → keyboard skip and Home/End jumps. Pass skipSeconds to override the ±10s default.' },
  { version: 'v1.21.0', date: '2026-05-28', type: 'docs', scope: 'ai', title: 'Terminal — replaced traffic-light dots with the terminal icon',
    summary: 'The Terminal header swapped the three macOS-style traffic-light dots for a single ember Icons.terminal — more Eidos, less skeuomorphic.' },

  // ─── v1.20.0 — Ask UX rebuild + SpeechInput compact (2026-05-28) ──────
  { version: 'v1.20.0', date: '2026-05-28', type: 'feat', scope: 'ai', title: 'Ask — full UX rebuild with stepped flow, slide transitions, Back/keyboard nav',
    summary: 'AskUser was rebuilt for real interactive feel. Auto-advance after a 180ms confirmation beat lets the user actually SEE their pick before the next question slides in. Back link returns one step. Keyboard: 1–9 pick by number, ↑/↓ move focused option, Enter selects, ⌃↵ advances multi-select. A subtle ember progress bar shows position. The completed state lists answers + Restart. Selection is communicated by ember-soft background + an ember-highlighted number badge on the trailing edge — no more "AI-chatbot" left-bar accent. Number badges are always visible (quiet by default, brighter on hover/focus, ember when selected). Skip moved from the header to the footer, sitting left of Continue.' },
  { version: 'v1.20.0', date: '2026-05-28', type: 'fix', scope: 'ai', title: 'Ask — auto-advance was silently dropping under concurrent mode',
    summary: 'The setTimeout that drove auto-advance after a single-select click was scheduled INSIDE a setAnswers updater function (a React anti-pattern: updaters must be pure, and concurrent mode can run or discard them more than once). Moved the side-effect outside the updater. Auto-advance now fires reliably.' },
  { version: 'v1.20.0', date: '2026-05-28', type: 'feat', scope: 'ai', title: 'Ask — Continue button appears when "Other" has text',
    summary: 'Previously, single-select + allowOther had no way to commit a typed free-text answer (option clicks auto-advanced; typing in Other did nothing). Now the Continue/Finish CTA appears the moment the user types something in the Other input, so the typed text can actually be submitted. Auto-advance on regular option click is unchanged.' },
  { version: 'v1.20.0', date: '2026-05-28', type: 'docs', scope: 'ai', title: 'Ask — slide transitions, header layout, hint row',
    summary: 'Cross-fade replaced by a clean slide via @keyframes (the question element is keyed by step and remounts on change; slide direction comes from is-next / is-prev on the wrapper). The header is now: topic · "Question N of M" on the leading edge + a small 80×2px progress bar on the trailing edge. The keyboard hints (↑↓ navigate · 1–N pick · ⌃↵ continue) moved out of the footer into a quiet hint row below the options, aligned to the leading edge. Panel mode (stepped={false}) was removed — Ask is stepped-only now.' },
  { version: 'v1.20.0', date: '2026-05-28', type: 'feat', scope: 'speech-input', title: 'SpeechInput compact variant for the PromptInput footer',
    summary: 'New compact prop renders SpeechInput as a single .pi-tool icon button (matches the paperclip exactly) instead of the bordered full surface — so it slots into <PromptInput footerTools={…}/> without dominating the row. State machine intact: idle is the resting style, listening fills ember + pulses, processing tints ember-soft, error tints danger. The full surface is still the right call for the dedicated voice screen.' },

  // ─── v1.19.0 — Artifacts + Voice (2026-05-28) ──────
  { version: 'v1.19.0', date: '2026-05-28', type: 'feat', scope: 'ai', title: 'Artifact — widget + side panel for model-produced things',
    summary: 'Two new core components: ArtifactWidget (a compact chip that lands in a Message bubble — title + kind + meta + open arrow) and ArtifactPanel (the docked side-panel host with header + optional tabs + scrollable body). Supports four kinds — document / html / app / code — with sensible defaults per kind plus full slot override. The canonical pattern: chat on the left, artifact docked on the right.' },
  { version: 'v1.19.0', date: '2026-05-28', type: 'feat', scope: 'ai', title: 'Terminal — paired commands + output surface',
    summary: 'New Terminal component for showing what an agent ran and what came back — title bar with traffic-light dots + optional status pill, mono command lines with ember $ prompt, output lines, danger-toned err lines, and italic note dividers. role="log" + aria-live polite while running. For unbounded log streams, prefer core LogViewer (cross-linked).' },
  { version: 'v1.19.0', date: '2026-05-28', type: 'docs', scope: 'ai', title: 'JSX Preview — the live-render pattern (doc-only)',
    summary: 'A doc page demonstrating the JSX preview pattern (textarea ↔ live render) without shipping a JSX evaluator in core. Includes a tiny new-Function preview for the doc demos and a recommended path for production (react-live / sandboxed iframe).' },
  { version: 'v1.19.0', date: '2026-05-28', type: 'feat', scope: 'ai', title: 'Voice — Persona, SpeechInput, Transcription, AudioPlayer',
    summary: 'New core/ai/voice.tsx with four components for audio AI surfaces. Persona — the ember-gradient orb with four states (idle / listening / thinking / speaking), each with its own CSS animation; SpeechInput — mic button + waveform + transcript preview + state machine (idle / listening / processing / error); Transcription — speaker-labeled lines with optional time and confidence; AudioPlayer — minimal play/scrub/mute over a real <audio>. All animation respects prefers-reduced-motion. Icons.tsx also gained mic / pause / volume / volumeOff.' },

  // ─── v1.18.1 — Portal stretch + Sources chevron + Ask anatomy (2026-05-28) ──────
  { version: 'v1.18.1', date: '2026-05-28', type: 'fix', scope: 'prompt-input', title: 'ModelSelector portal no longer stretches the viewport',
    summary: 'The portaled menu was inheriting the base .pi-menu positioning and over-expanding. Now: position/height enforced inline AND with !important on the .pi-menu--portal class (bottom: auto, right: auto, height: auto, max-height: 360, overflow-y: auto). The menu is also measured via useLayoutEffect before placement (no first-frame flash), and flips below the trigger when there is no room above.' },
  { version: 'v1.18.1', date: '2026-05-28', type: 'fix', scope: 'citations', title: 'Sources — chevron moved to the trailing edge + count noun',
    summary: 'Header now mirrors ChainOfThought: "Sources · 3 findings ⌄" — chevron at the end, rotates 180° on open. New countNoun prop (default "findings") customises the pluralised label.' },
  { version: 'v1.18.1', date: '2026-05-28', type: 'docs', scope: 'ai', title: 'Ask — anatomy legend updated to the flat layout',
    summary: 'The Anatomy stage no longer references tick / radio dots (the flat rebuild removed them). Legend now describes: header (topic + step + skip), title, option row with title + description, and the ember-soft background fill as the selection cue.' },

  // ─── v1.18.0 — Context window + portaled model menu (2026-05-28) ──────
  { version: 'v1.18.0', date: '2026-05-28', type: 'feat', scope: 'contexts', title: 'ContextGauge — the context-window indicator',
    summary: 'New core/ai/context.tsx module with <ContextGauge/> (compact radial, "8.2k / 200k · 3 files") and <ContextBar/> (linear variant). Tone shifts at 60% (warning) and 85% (danger). Embeddable in PromptInput via a stable new contextSlot prop — sits before the model selector. Speaks the two facets of "context" together: the files the agent is grounded on, and how much of the model’s window is spent.' },
  { version: 'v1.18.0', date: '2026-05-28', type: 'fix', scope: 'prompt-input', title: 'ModelSelector menu now portals out of the composer',
    summary: 'The model dropdown was clipped by PromptInput’s container. The menu now renders via React portal at document.body, positioned by getBoundingClientRect on the trigger (re-measured on scroll/resize). Outside-click and Escape still close it; arrow keys still navigate.' },
  { version: 'v1.18.0', date: '2026-05-28', type: 'feat', scope: 'citations', title: 'Sources — chevron disclosure + pagination',
    summary: 'Sources panel now has a chevron-triggered open/close header (matching ChainOfThought) and paginates when sources.length > 5 (perPage prop). Leading/trailing arrow buttons with a "1–5 of 12" position indicator.' },
  { version: 'v1.18.0', date: '2026-05-28', type: 'feat', scope: 'ai', title: 'Ask — clean-room rebuild after fluidfunctionalism',
    summary: 'AskUser rebuilt from scratch to mirror the fluidfunctionalism.com Ask component, customizing colors to Eidos. Sans throughout (no mono uppercase eyebrows), demure "Question N of M" header, confident 20px semibold title, options as flat rows separated by whitespace, selection by ember-soft background fill (no tick icons, title stays var(--fg) — the fill IS the cue). New inline layout for short descriptions. Filled ember Next/Finish CTA with ⌃↵ keyboard hint.' },

  // ─── v1.17.1 — Flat refinement (2026-05-28) ──────
  { version: 'v1.17.1', date: '2026-05-28', type: 'docs', scope: 'ai', title: 'Ask · Sources · Checkpoint · Chain of Thought refined to a flatter, typographic style',
    summary: 'Killed the "box-within-box" chrome: outer card borders, per-row borders, circular step marks, connector lines, and tick chips are gone. Structure is now carried by typography + spacing + hairlines, with ember-soft background as the selected state (matching the fluidfunctionalism Ask reference). Markup also flattened — AskUser no longer renders tick spans, Checkpoint no longer renders a chip pill.' },

  // ─── v1.17.0 — Agentic + Ask (2026-05-28) ──────
  { version: 'v1.17.0', date: '2026-05-28', type: 'feat', scope: 'agents', title: 'Ask — the assistant turns the question around',
    summary: 'New AskUser component: a stepped (or single-panel) flow of questions with 2–5 options each, single or multi-select, an optional free-text "other" escape, skippable questions, and a completed-state read-only summary. ⌃↵ to advance. The agent stops guessing and asks before committing.' },
  { version: 'v1.17.0', date: '2026-05-28', type: 'feat', scope: 'agents', title: 'Agentic surfaces — Plan, Task, Chain of Thought, Checkpoint, Confirmation, Queue',
    summary: 'Six new agentic primitives shipped to core/ai: Plan (the ordered todo the agent ticks off), Task (one unit of work + subtasks), ChainOfThought (legible stepped trace, richer than Reasoning), Checkpoint (turn-level save-point with Restore), Confirmation (agent asks before doing something consequential — default/danger tone, pending→confirmed/cancelled), Queue (lined-up prompts during a long run). Each ships with its own §2.2 documentation page.' },
  { version: 'v1.17.0', date: '2026-05-28', type: 'feat', scope: 'prompt-input', title: 'Model Selector — own page + keyboard a11y',
    summary: 'ModelSelector got its own §2.2 page documenting controlled use, custom model lists, and the canonical placement inside PromptInput / conversation headers. The core component picked up arrow-key navigation (ArrowUp/Down/Home/End/Enter), aria-activedescendant, aria-current on the selected model, and a listbox role.' },

  // ─── v1.16.0 — Content blocks (2026-05-27) ──────
  { version: 'v1.16.0', date: '2026-05-27', type: 'feat', scope: 'markdown', title: 'Content blocks: Code, Mermaid, Math, Image, CJK, Shimmer',
    summary: 'Six new content surfaces for model replies — Code block (reuses core CodeBlock + a live Shiki highlight demo), Mermaid (diagram slot + live render), Math (KaTeX slot, inline + display), Image (ImageView with loading shimmer + error fallback), CJK (lang-aware Prose/Message typography), and Shimmer/Skeleton loading affordances. New dep-free core/ai/content.tsx components: Shimmer, Skeleton, ImageView, Diagram, MathView.' },
  { version: 'v1.16.0', date: '2026-05-27', type: 'feat', scope: 'citations', title: 'Citations / Sources split',
    summary: 'Citations now focuses on the inline numbered chip + popover; the standalone Sources panel/list moved to its own page. Both reuse the core Citation / Sources components.' },

  // ─── v1.15.0 — Identity + Markdown + Prompt Input (2026-05-27) ──────
  { version: 'v1.15.0', date: '2026-05-27', type: 'feat', scope: 'agents', title: 'Agent identity — AgentAvatar, AgentIdentity, AgentCard',
    summary: 'How an agent is identified is now a primitive: AgentAvatar (the squircle bot mark with presence dot), AgentIdentity (avatar + name + model line), and the reused core AgentCard. The Agent page was rebuilt to the §2.2 standard covering the mark, presence/persona, the card, and the run loop.' },
  { version: 'v1.15.0', date: '2026-05-27', type: 'feat', scope: 'prompt-input', title: 'PromptInput with full state coverage',
    summary: 'PromptInput is a composite core component (status ready/submitted/streaming/error, disabled, invalid, onStop, attachments, model selector). The page documents every state — idle, typing, submitting, streaming-with-stop, disabled, error — plus drag-and-drop and the model selector, to §2.2.' },
  { version: 'v1.15.0', date: '2026-05-27', type: 'docs', scope: 'markdown', title: 'Markdown surface — full feature coverage + live render',
    summary: 'The Markdown page now showcases every feature (headings, lists, task lists, tables, blockquotes, code, inline formats) and a live react-markdown → Prose pipeline (remark-gfm + rehype-sanitize), with fenced code routed to ProseCode. AILabel also moved into core/ai so any surface can compose it.' },

  // ─── v1.14.0 — AI component layer (2026-05-27) ──────
  { version: 'v1.14.0', date: '2026-05-27', type: 'feat', scope: 'ai', title: 'AI components extracted into core/ai — importable from @/ds/core',
    summary: 'Every AI surface that used to be re-implemented inline per page is now a shared DS-core component: Response, Prose, ProseCode, MessageActions, AICaret, Tool, Reasoning, Citation, Sources, PromptInput, ModelSelector, Suggestion, Conversation and History all live in core/ai and import from @/ds/core. The Markdown / Response / Streaming overlap collapsed onto one Prose surface + one streaming caret.' },
  { version: 'v1.14.0', date: '2026-05-27', type: 'tokens', scope: 'ai', title: 'AI styles consolidated into ai.css — no more per-page <style>',
    summary: 'All .ai-*/.msg-* rules moved out of ds.css and the six page-local <style> blocks (tool, reasoning, suggestion, prompt-input, conversation, label) were lifted into a dedicated src/styles/ai.css, removing the per-page style invariant violations.' },

  // ─── v1.10.0 — Page standard (2026-05-22) ──────
  { version: 'v1.10.0', date: '2026-05-22', type: 'docs', scope: 'ai', title: 'Accessibility section on every AI surface',
    summary: 'Every AI page got a sharpened lede and a required Accessibility section with surface-specific guidance: aria-live="polite" for streaming, focus order and roles for the conversation/prompt input, the disclosure/expanded state for tool calls and reasoning, and a reduced-motion fallback that drops the typing caret to instant text.' },

  // ─── v1.9.0 — AI becomes its own sub-DS (2026-05-21) ──────
  { version: 'v1.9.0', date: '2026-05-21', type: 'feat', scope: 'ai', title: 'Eidos AI split into its own sub-DS at /ai',
    summary: 'Message, conversation, prompt input, streaming, markdown, reasoning, tool, agents, contexts, citations, errors, history, suggestion and AI Label moved into a dedicated AI sub-DS, route-prefixed at /ai. No new palette — AI surfaces compose the same core primitives, tokens and ember accent.' },
  { version: 'v1.9.0', date: '2026-05-21', type: 'feat', scope: 'overview', title: 'Overview rebuilt — a live streaming chat in the hero',
    summary: 'New Introduction-style Overview whose hero is a working mini chat: a user bubble, a "getServiceHealth · done" tool chip, and an assistant answer that types out token-by-token with the streaming caret (fixed-width surface, looping).' },
  { version: 'v1.9.0', date: '2026-05-21', type: 'feat', scope: 'streaming', title: 'Streaming, Markdown, Contexts, Agents pages added',
    summary: 'Filled out the AI surface set: token-by-token Streaming (with the caret), rendered Markdown (prose, code, lists, tables), grounding Contexts (sources / files / scope chips), and the Agents loop (plan → call → answer).' },
  { version: 'v1.8.0', date: '2026-05-17', type: 'tokens', scope: 'ai', title: 'AI surfaces migrated to --ember-fg / --danger-fg',
    summary: 'The AI conversation badge and the prompt-input send button dropped hardcoded #08090A / #FFFFFF for theme-aware var(--ember-fg) — primary surfaces now flip correctly between light and dark.' },
  { version: 'v1.1.0', date: '2026-05-14', type: 'feat', scope: 'citations', title: 'Citations component',
    summary: 'Inline numbered chips + a sources panel for assistant responses with attributable sources.' },
  { version: 'v1.1.0', date: '2026-05-14', type: 'feat', scope: 'errors', title: 'AI error states',
    summary: 'Model-down, rate-limited, refusal, context-overflow, network-timeout and partial-failure — all six surfaces with copy + recovery CTAs.' },
  { version: 'v1.1.0', date: '2026-05-14', type: 'feat', scope: 'history', title: 'Conversation history sidebar',
    summary: 'Date-grouped thread list with search, starred items, and rename / delete on hover.' },
  { version: 'v1.1.0', date: '2026-05-14', type: 'feat', scope: 'message', title: 'Message extracted to an atom',
    summary: 'Deduped ~226 lines across four AI pages into a single Message primitive — user / assistant / system turns share one component.' },
];

export default function AiChangelog() {
  return (
    <ChangelogView
      entries={CHANGELOG}
      title="Changelog"
      desc="Every change to Eidos AI — searchable, filterable, scoped per surface."
      dsName="Eidos AI"
    />
  );
}
