// AUTO-GENERATED by scripts/gen-examples.mjs — do not edit by hand.
// Standalone IDP example screens (rendered at /example/<name>, no docs shell).
/* eslint-disable */
import type { ComponentType } from 'react';

export const EXAMPLES_REG: Record<string, () => Promise<{ default: ComponentType }>> = {
  "agent-catalog": () => import('./agent-catalog'),
  "agent-chat": () => import('./agent-chat'),
  "ai-chat": () => import('./ai-chat'),
  "ai-chat-active": () => import('./ai-chat-active'),
  "ai-chat-artifacts": () => import('./ai-chat-artifacts'),
  "ai-chat-empty": () => import('./ai-chat-empty'),
  "ai-chat-search": () => import('./ai-chat-search'),
  "ai-chat-thread": () => import('./ai-chat-thread'),
  "ai-insights": () => import('./ai-insights'),
  "ai-project-detail": () => import('./ai-project-detail'),
  "ai-projects": () => import('./ai-projects'),
  "chat-shell": () => import('./chat-shell'),
  "cloud-inventory": () => import('./cloud-inventory'),
  "dora-dashboard": () => import('./dora-dashboard'),
  "feature-flags": () => import('./feature-flags'),
  "incident-room": () => import('./incident-room'),
  "mcp-detail": () => import('./mcp-detail'),
  "pipeline-console": () => import('./pipeline-console'),
  "pipeline-view": () => import('./pipeline-view'),
  "quality-gates": () => import('./quality-gates'),
  "ring-deployment": () => import('./ring-deployment'),
  "score-cards": () => import('./score-cards'),
  "service-catalog": () => import('./service-catalog'),
  "service-detail": () => import('./service-detail'),
  "service-scaffold": () => import('./service-scaffold'),
  "templates": () => import('./templates'),
};
