import * as React from 'react';
import type { Meta, StoryObj } from '@storybook/react-vite';
import { ProseCode } from '@forge/ui';

const meta = {
  title: 'AI/ProseCode',
  component: ProseCode,
  tags: ['autodocs'],
  parameters: {
    layout: 'padded',
    docs: {
      description: {
        component:
          'A prose-scoped code block used inside `.ai-prose` responses. Renders a ' +
          'language-labelled header, a copy-to-clipboard button (with transient "Copied" ' +
          'feedback), and a `<pre>` body. Use `ProseCode` when code appears inline inside ' +
          'a model response; for a standalone, fully-documented code block outside prose ' +
          'use the core `<CodeBlock>` primitive instead.',
      },
    },
  },
  argTypes: {
    lang: {
      control: 'text',
      description: 'Language label shown in the code-block header (e.g. "bash", "ts", "yaml").',
    },
    children: {
      control: false,
      description: 'Raw code string rendered inside the `<pre>` body.',
    },
  },
  args: {
    lang: 'bash',
    children: 'forge deploy --service fraud-engine --ring 0 --version 3.4.7',
  },
} satisfies Meta<typeof ProseCode>;

export default meta;
type Story = StoryObj<typeof meta>;

/** Minimal usage — a single shell command produced by an AI deploy assistant. */
export const Default: Story = {};

/** TypeScript snippet — a rollback helper generated by the agent. */
export const TypeScript: Story = {
  args: {
    lang: 'ts',
    children: [
      "import { deployctl } from '@forge/infra';",
      '',
      'async function rollback(service: string, version: string): Promise<void> {',
      '  await deployctl.rollback({',
      '    service,',
      '    version,',
      '    ring: 0,',
      '    dryRun: false,',
      '  });',
      "  console.log(`Rolled back ${service} to ${version}`);",
      '}',
    ].join('\n'),
  },
};

/** YAML — Kubernetes HPA config surfaced in a chat response. */
export const YAML: Story = {
  args: {
    lang: 'yaml',
    children: [
      'apiVersion: autoscaling/v2',
      'kind: HorizontalPodAutoscaler',
      'metadata:',
      '  name: fraud-engine-hpa',
      '  namespace: payments',
      'spec:',
      '  scaleTargetRef:',
      '    apiVersion: apps/v1',
      '    kind: Deployment',
      '    name: fraud-engine',
      '  minReplicas: 2',
      '  maxReplicas: 20',
      '  metrics:',
      '    - type: Resource',
      '      resource:',
      '        name: cpu',
      '        target:',
      '          type: Utilization',
      '          averageUtilization: 70',
    ].join('\n'),
  },
};

/**
 * Variants — a side-by-side layout showing bash, TypeScript, and JSON snippets
 * as they would appear in a real AI response, covering the common language matrix.
 */
export const Variants: Story = {
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 24, maxWidth: 680 }}>
      <ProseCode lang="bash">
        {'forge deploy --service pix-router --version 2.1.0 --ring canary'}
      </ProseCode>

      <ProseCode lang="ts">
        {[
          "import { IncidentClient } from '@forge/ops';",
          '',
          'const client = new IncidentClient({ region: \'sa-east-1\' });',
          "const incident = await client.open({ severity: 'p1', service: 'fraud-engine' });",
          'console.log(incident.id); // INC-9812',
        ].join('\n')}
      </ProseCode>

      <ProseCode lang="json">
        {JSON.stringify(
          {
            incident_id: 'INC-9812',
            service: 'fraud-engine',
            severity: 'p1',
            status: 'resolved',
            root_cause: 'stale feature store cache',
            resolved_at: '2024-11-14T14:47:00Z',
          },
          null,
          2,
        )}
      </ProseCode>
    </div>
  ),
};
