import type { Meta, StoryObj } from '@storybook/react-vite';
import { TabbedCode, installTabs } from '@eidos/ui';

const meta = {
  title: 'Primitives/TabbedCode',
  component: TabbedCode,
  tags: ['autodocs'],
  parameters: {
    docs: {
      description: {
        component:
          'Switchable code panes — a headed frame with pill tabs on the left and a copy button ' +
          '(always reflects the active tab) on the right. The canonical use is the Installation block: ' +
          'five tabs for pnpm / npm / yarn / bun / Manual, generated by the `installTabs(name)` factory.',
      },
    },
  },
  args: {
    tabs: installTabs('button'),
    defaultIndex: 0,
    ariaLabel: 'package manager',
  },
  argTypes: {
    defaultIndex: { control: 'number', description: 'Index of the initially active tab.' },
    ariaLabel: { control: 'text', description: 'Accessible label passed to the inner `tablist`.' },
  },
} satisfies Meta<typeof TabbedCode>;

export default meta;
type Story = StoryObj<typeof meta>;

/** Standard install block — five package managers via `installTabs`. */
export const Default: Story = {};

/** Custom multi-file switcher — two TypeScript snippets side by side. */
export const CustomTabs: Story = {
  args: {
    ariaLabel: 'example variant',
    tabs: [
      {
        label: 'Controlled',
        lang: 'tsx',
        code: `const [open, setOpen] = React.useState(false);\n\n<Dialog open={open} onOpenChange={setOpen}>\n  <DialogTrigger asChild>\n    <Button>Open dialog</Button>\n  </DialogTrigger>\n  <DialogContent>…</DialogContent>\n</Dialog>`,
      },
      {
        label: 'Uncontrolled',
        lang: 'tsx',
        code: `<Dialog>\n  <DialogTrigger asChild>\n    <Button>Open dialog</Button>\n  </DialogTrigger>\n  <DialogContent>…</DialogContent>\n</Dialog>`,
      },
    ],
    defaultIndex: 0,
  },
};

/** Opens on the Manual tab (index 4) — shows the full markdown-style instructions. */
export const ManualInstall: Story = {
  args: {
    tabs: installTabs('badge'),
    defaultIndex: 4,
  },
};
