import * as React from 'react';
// Forge AI — agent identity.
//
// How an agent shows up in the UI: its mark (AgentAvatar), its inline name +
// model line (AgentIdentity), the "this is AI" badge (AILabel), and — for a
// richer surface — the existing core <AgentCard/> (blocks.tsx) which this
// layer reuses rather than replicates. Styles live in src/styles/ai.css.
import { Icons } from '../icons';

// ── Spark — the 4-point Forge sparkle, the AI glyph ───────────────────────
const Spark = ({ size = 10 }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" aria-hidden="true">
    <path d="M 12 1 C 12 6, 18 12, 23 12 C 18 12, 12 18, 12 23 C 12 18, 6 12, 1 12 C 6 12, 12 6, 12 1 Z" fill="currentColor"/>
  </svg>
);

// ── AILabel — flags AI-generated content ──────────────────────────────────
// box (22px tile) · mark (text+sparkle) · pill (tinted) · dot (icon-only).
// One colour (ember), one label ("AI"). `interactive` makes it a real button.
const AILabel = ({
  variant = 'mark',
  size = 'md',
  revoked = false,
  interactive = false,
  onClick,
  children,
  style,
}: {
  /** Visual flavor. box=22px tile, mark=text+sparkle, pill=tinted background, dot=icon-only. */
  variant?: 'box' | 'mark' | 'pill' | 'dot';
  /** Scale. sm=18px, md=22px, lg=28px. */
  size?: 'sm' | 'md' | 'lg';
  /** When true, renders strikethrough + muted color to flag rejected AI output. */
  revoked?: boolean;
  /** Renders as a button with focus ring + keyboard support. Pair with onClick. */
  interactive?: boolean;
  /** Fires on click/Enter/Space when interactive=true. */
  onClick?: React.MouseEventHandler<HTMLSpanElement>;
  /** Text label. Defaults to "AI"; pass any short token (Beta, ML, GPT) if needed. */
  children?: React.ReactNode;
  /** Inline styles merged onto the root span. */
  style?: React.CSSProperties;
}) => {
  const text = children || 'AI';

  const cls = ['ai-label', variant];
  if (size !== 'md') cls.push(size);
  if (revoked) cls.push('revoked');
  if (interactive) cls.push('is-trigger');

  const onKey = interactive
    ? (e: React.KeyboardEvent<HTMLSpanElement>) => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); if (onClick) onClick(e as unknown as React.MouseEvent<HTMLSpanElement>); } }
    : undefined;

  return (
    <span
      className={cls.join(' ')}
      role={interactive ? 'button' : undefined}
      tabIndex={interactive ? 0 : undefined}
      onClick={onClick}
      onKeyDown={onKey}
      aria-label={interactive ? 'AI-generated content — view source' : 'AI-generated content'}
      style={style}
    >
      <span className="ai-glyph"><Spark/></span>
      <span className="ai-text">{text}</span>
    </span>
  );
};

// ── AILabelWithPopover — badge that reveals model / when / confidence ─────
const AILabelWithPopover = ({
  variant = 'pill',
  size = 'md',
  label = 'AI summary',
  model = 'forge-ai/gpt-4o-mini',
  ts = '2 min ago',
  confidence = 0.92,
  children,
}: {
  /** Trigger flavor — see AILabel variants. */
  variant?: 'box' | 'mark' | 'pill' | 'dot';
  /** Scale of the trigger badge. */
  size?: 'sm' | 'md' | 'lg';
  /** Title shown at the top of the popover. */
  label?: string;
  /** Model identifier. Mono-rendered in the metadata row. */
  model?: string;
  /** When the AI value was produced. Free-form string ("2 min ago", "2024-11-04"). */
  ts?: string;
  /** Confidence score 0–1. Rendered as a percentage in the popover. */
  confidence?: number;
  /** Short description shown in the popover body. */
  children?: React.ReactNode;
}) => {
  const desc = children || 'This value was generated by an AI model.';

  const [open, setOpen] = React.useState(false);
  const ref = React.useRef<HTMLSpanElement>(null);

  React.useEffect(() => {
    if (!open) return;
    const onDoc = (e: MouseEvent) => { if (ref.current && !ref.current.contains(e.target as Node)) setOpen(false); };
    const onKey = (e: KeyboardEvent) => { if (e.key === 'Escape') setOpen(false); };
    document.addEventListener('mousedown', onDoc);
    document.addEventListener('keydown', onKey);
    return () => {
      document.removeEventListener('mousedown', onDoc);
      document.removeEventListener('keydown', onKey);
    };
  }, [open]);

  return (
    <span className="ai-pop-anchor" ref={ref}>
      <AILabel variant={variant} size={size} interactive onClick={() => setOpen(!open)}>AI</AILabel>
      {open ? (
        <div className="ai-pop" role="dialog" aria-label="AI source">
          <div className="ai-pop-head">
            <AILabel variant="box" size="sm"/>
            <span>{label}</span>
          </div>
          <p className="ai-pop-desc">{desc}</p>
          <dl className="ai-pop-meta">
            <dt>Model</dt><dd>{model}</dd>
            <dt>When</dt><dd>{ts}</dd>
            <dt>Confidence</dt><dd>{Math.round(confidence * 100) + '%'}</dd>
          </dl>
          <div className="ai-pop-actions">
            <button className="btn xs ember">Accept</button>
            <button className="btn xs ghost">Edit</button>
            <button className="btn xs ghost" onClick={() => setOpen(false)}>Revoke</button>
          </div>
        </div>
      ) : null}
    </span>
  );
};

// ── AgentAvatar — the agent's mark ────────────────────────────────────────
// Reuses the core `.avatar` chrome (circular, ember tint) + the presence
// `.status-dot`. Default glyph is the agent icon; pass `glyph` to override
// (or `initials` for a named persona). Contrast holds because it reuses the
// proven ember-avatar styling (ember glyph on ember-soft elevated).
//   size      number (px)
//   status    "online" | "away" | "offline" | "busy"
//   ember     boolean (default true)
//   glyph     ReactNode — override the icon
//   initials  string — render initials instead of a glyph
const AgentAvatar = ({
  size = 32,
  status,
  ember = true,
  glyph,
  initials,
  name,
  className,
  style,
}: {
  /** Avatar diameter in px. */
  size?: number;
  /** Presence dot variant. "online" shows green; "away" amber; "offline" grey; "busy" red. */
  status?: 'online' | 'away' | 'offline' | 'busy';
  /** When true, applies the ember tint (default true). Set false for user avatars. */
  ember?: boolean;
  /** Override the default agent icon with any ReactNode. */
  glyph?: React.ReactNode;
  /** Render initials instead of the glyph icon. */
  initials?: string;
  /** Accessible name for the avatar (used in title attribute). */
  name?: string;
  /** Extra class names applied to the root span. */
  className?: string;
  /** Inline styles merged onto the root span. */
  style?: React.CSSProperties;
}) => {
  const cls = ['avatar', 'ai-agent-avatar'];
  if (ember) cls.push('ember');
  if (size >= 40) cls.push('lg');
  if (className) cls.push(className);
  return (
    <span className={cls.join(' ')} style={{ width: size, height: size, ...style }} title={name}>
      {initials
        ? <span style={{ fontSize: Math.round(size * 0.36) }}>{initials}</span>
        : (glyph || <Icons.agent size={Math.round(size * 0.5)}/>)}
      {status && <span className={'status-dot' + (status !== 'online' ? ' ' + status : '')} aria-hidden="true"/>}
    </span>
  );
};

// ── AgentIdentity — inline "who is talking" row ───────────────────────────
// Avatar + name + model line, with an optional AI label and presence. The
// canonical way an agent is identified in a meta row / header.
//   agent  { name, model, status }
//   size   avatar px (default 32)
//   label  boolean — append an <AILabel/> after the name
const AgentIdentity = ({
  agent = {},
  size = 32,
  label = false,
  className,
  style,
}: {
  /** Agent descriptor — name, model id, and optional presence status. */
  agent?: { name?: string; model?: string; status?: 'online' | 'away' | 'offline' | 'busy' };
  /** Avatar diameter in px. Controls the AgentAvatar inside this row. */
  size?: number;
  /** When true, appends an AILabel pill after the agent name. */
  label?: boolean;
  /** Extra class names applied to the root span. */
  className?: string;
  /** Inline styles merged onto the root span. */
  style?: React.CSSProperties;
}) => (
  <span className={'ai-agent-id' + (className ? ' ' + className : '')} style={style}>
    <AgentAvatar size={size} status={agent.status} name={agent.name}/>
    <span className="ai-agent-id-text">
      <span className="ai-agent-id-name">
        {agent.name || 'Forge AI'}
        {label && <AILabel variant="pill" size="sm">AI</AILabel>}
      </span>
      {agent.model && <span className="ai-agent-id-model">{agent.model}</span>}
    </span>
  </span>
);

export { Spark, AILabel, AILabelWithPopover, AgentAvatar, AgentIdentity };
