// GENERATED by scripts/gen-system.mjs — DO NOT EDIT.
// Typed token vocabularies for the <Box> layout primitive. Source: packages/ui/styles/tokens.css.
// A value outside these unions is not expressible — it fails to compile.

export const SPACE_TOKENS = ['0', 'px', '1', '2', '3', '4', '5', '6', '8', '10', '12', '16', '24'] as const;
export type SpaceToken = (typeof SPACE_TOKENS)[number];

export const RADIUS_TOKENS = ['xs', 'sm', 'md', 'lg', 'xl', '2xl', 'full'] as const;
export type RadiusToken = (typeof RADIUS_TOKENS)[number];

export const BACKGROUND_TOKENS = ['canvas', 'bg', 'bg-elevated', 'surface', 'surface-hover', 'surface-overlay', 'surface-active', 'surface-selected', 'accent', 'ember', 'ember-soft', 'ember-softer', 'success', 'success-soft', 'warning', 'warning-soft', 'danger', 'danger-soft', 'info', 'info-soft'] as const;
export type BackgroundToken = (typeof BACKGROUND_TOKENS)[number];

export const BORDER_TOKENS = ['border', 'border-subtle', 'border-strong', 'border-stronger', 'ember-border', 'success-border', 'warning-border', 'danger-border', 'info-border'] as const;
export type BorderToken = (typeof BORDER_TOKENS)[number];

export const TEXT_TOKENS = ['fg', 'fg-muted', 'fg-subtle', 'fg-faint', 'accent', 'ember', 'ember-text', 'success-text', 'warning-text', 'danger-text', 'info-text'] as const;
export type TextToken = (typeof TEXT_TOKENS)[number];

export const DISPLAY_VALUES = ['flex', 'grid', 'block', 'inline-flex', 'inline-block', 'none'] as const;
export type Display = (typeof DISPLAY_VALUES)[number];

export const DIRECTION_VALUES = ['row', 'col', 'row-reverse', 'col-reverse'] as const;
export type Direction = (typeof DIRECTION_VALUES)[number];

export const ALIGN_VALUES = ['start', 'center', 'end', 'stretch', 'baseline'] as const;
export type Align = (typeof ALIGN_VALUES)[number];

export const JUSTIFY_VALUES = ['start', 'center', 'end', 'between', 'around', 'evenly'] as const;
export type Justify = (typeof JUSTIFY_VALUES)[number];

export const WRAP_VALUES = ['wrap', 'nowrap', 'wrap-reverse'] as const;
export type Wrap = (typeof WRAP_VALUES)[number];

export const SIZE_VALUES = ['full', 'auto', 'fit'] as const;
export type Size = (typeof SIZE_VALUES)[number];

export const FLEX_VALUES = ['1', 'auto', 'none'] as const;
export type FlexValue = (typeof FLEX_VALUES)[number];

export const COLUMN_VALUES = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12'] as const;
export type GridColumns = (typeof COLUMN_VALUES)[number];
