// eidos-health.mjs — renders EIDOS-HEALTH.md, the generated health wall, from
// reports/state.json. NEVER hand-edited (it's in protect-generated.mjs's blocklist).
//
//   node scripts/eidos-health.mjs   # re-render from the committed state.json
//
// Also exports renderHealth(state, contract) so forge-verify regenerates it inline.
import { readFileSync } from 'node:fs';
import { abs, STATE_PATH, loadContract } from './eidos-lib.mjs';

const MARK = { pass: '✅', fail: '❌', partial: '⚠️', waived: '〰', skip: '·' };

// the columns shown in the wall, by clause id → short label
const COLS = [
  ['C-docs-exists', 'Docs'],
  ['C-export', 'Export'],
  ['C-story', 'Story'],
  ['C-registry', 'Registry'],
  ['C-a11y-axe', 'A11y'],
  ['C-rtl-frame', 'RTL'],
  ['C-docs-sections', 'Sect'],
  ['C-contrast-fill', 'Contrast'],
];

function cell(entry, clauseId) {
  const c = entry.clauses[clauseId];
  if (!c) return ' ';
  return MARK[c.status] || '?';
}

export function renderHealth(state, contract = loadContract()) {
  const s = state.summary;
  const lines = [];
  lines.push(`# Eidos component health  ·  contract ${state.contractVersion}  ·  DS ${state.dsVersion}  ·  ${state.commit || 'local'}  ·  generated ${state.generatedAt.slice(0, 10)}`);
  lines.push('');
  lines.push(`${s.done} / ${s.components} done · ${s.blockFails} block-fails · ${s.waived} waived · ${s.advisoryFails} advisory-fails · ${s.skipped} skipped`);
  lines.push('');
  lines.push('> Generated by `npm run eidos:verify`. Do not edit by hand.');
  lines.push('');

  // table
  const header = ['Component', ...COLS.map(([, l]) => l), 'Status'];
  const align = ['-----------', ...COLS.map(() => ':----:'), ':----:'];
  lines.push(`| ${header.join(' | ')} |`);
  lines.push(`| ${align.join(' | ')} |`);
  const names = Object.keys(state.components).sort();
  for (const name of names) {
    const e = state.components[name];
    const row = [name.padEnd(11), ...COLS.map(([id]) => cell(e, id)), MARK[e.status] === '✅' ? '✓' : MARK[e.status] === '❌' ? '✗' : '~'];
    lines.push(`| ${row.join(' | ')} |`);
  }
  lines.push('');
  lines.push('(✅ pass · ❌ block-fail · ⚠️ advisory-fail · 〰 waived · · skipped)');
  lines.push('');

  // debt — block-fails first, then advisory; rank by fewest failing clauses to green
  const debt = [];
  for (const name of names) {
    const e = state.components[name];
    for (const [id, c] of Object.entries(e.clauses)) {
      if (c.status === 'fail') debt.push({ name, id, gate: c.gate, detail: c.detail || '' });
    }
  }
  debt.sort((a, b) => (a.gate === b.gate ? 0 : a.gate === 'block' ? -1 : 1));
  lines.push('## Debt (block-fails first)');
  if (!debt.length) lines.push('- none 🎉');
  for (const d of debt.slice(0, 80)) lines.push(`- ${d.name} · ${d.id} (${d.gate})${d.detail ? ` — ${d.detail}` : ''}`);
  lines.push('');

  // waivers
  const waivers = (contract.waivers || []);
  lines.push('## Waivers (reviewed exceptions)');
  if (!waivers.length) lines.push('- none');
  for (const w of waivers) lines.push(`- ${w.component} · ${w.clause} — ${w.reason}${w.expires ? ` (expires ${w.expires})` : ''}`);
  lines.push('');

  // per-surface coverage
  const cov = Object.entries(state.surfaces).map(([k, v]) => `${k} ${Math.round(v * 100)}%`).join(' · ');
  lines.push('## Per-surface coverage');
  lines.push(cov || '(none yet)');
  lines.push('');

  return lines.join('\n');
}

if (import.meta.url === `file://${process.argv[1]}`) {
  let state;
  try { state = JSON.parse(readFileSync(abs(STATE_PATH), 'utf8')); }
  catch { console.error('No reports/state.json — run `npm run eidos:verify -- --all` first.'); process.exit(1); }
  process.stdout.write(renderHealth(state));
}
