// Eidos "System" layer generator — the LLM-safe typed layout vocabulary.
//
// Reads the canonical token source (packages/ui/styles/tokens.css) and emits, in
// lock-step, two artifacts that together turn layout into a strongly-typed language:
//
//   1. packages/ui/src/system/tokens.gen.ts   — token unions + value arrays (TS types)
//   2. packages/ui/styles/system.gen.css       — the atomic utility classes the
//                                                primitives compose (one class per
//                                                prop×token), authored with LOGICAL
//                                                CSS properties (RTL-first, an Eidos
//                                                invariant).
//
// The <Box> primitive composes class names by template (`eb-p-${token}`); because the
// class names here and the token unions in tokens.gen.ts derive from the SAME source,
// the type system can only express a value the stylesheet actually defines. A token the
// CSS does not ship is not a member of the union → it fails to compile. That is the
// whole point: the wrong thing does not type-check.
//
//   node scripts/gen-system.mjs            # write both artifacts
//   node scripts/gen-system.mjs --check    # exit 1 if either committed file is stale
import { readFileSync, writeFileSync, existsSync } from 'node:fs';

const SOURCES = ['packages/ui/styles/tokens.css', 'src/styles/tokens.css'];
const SOURCE = SOURCES.find((p) => existsSync(p));
if (!SOURCE) { console.error(`gen-system: no token source (looked for ${SOURCES.join(', ')})`); process.exit(1); }
const css = readFileSync(SOURCE, 'utf8');
const has = (name) => new RegExp(`--${name}\\s*:`).test(css);

// Validate a curated allowlist against the real token source; drop (with a warning)
// anything the source does not actually ship, so we never emit a class bound to a
// non-existent CSS variable.
function check(kind, names) {
  const missing = names.filter((n) => !has(n));
  if (missing.length) console.warn(`gen-system: ${kind} tokens not found in ${SOURCE}, skipping: ${missing.join(', ')}`);
  return names.filter((n) => has(n));
}

// ── Token vocabularies ──────────────────────────────────────────────────────
// Spacing & radius keys map to --space-<key> / --radius-<key>. Order is curated
// (numeric-ish) so the generated union reads predictably.
const SPACE = check('space', ['0', 'px', '1', '2', '3', '4', '5', '6', '8', '10', '12', '16', '24'].map((k) => `space-${k}`))
  .map((n) => n.replace(/^space-/, ''));
const RADIUS = check('radius', ['xs', 'sm', 'md', 'lg', 'xl', '2xl', 'full'].map((k) => `radius-${k}`))
  .map((n) => n.replace(/^radius-/, ''));

// Color roles. Keys ARE the token names (background-color / border / color use the
// var directly). Curated to the roles meaningful on a layout surface.
const BG = check('background', ['canvas', 'bg', 'bg-elevated', 'surface', 'surface-hover', 'surface-overlay', 'surface-active', 'surface-selected', 'accent', 'ember', 'ember-soft', 'ember-softer', 'success', 'success-soft', 'warning', 'warning-soft', 'danger', 'danger-soft', 'info', 'info-soft']);
const BORDER = check('border', ['border', 'border-subtle', 'border-strong', 'border-stronger', 'ember-border', 'success-border', 'warning-border', 'danger-border', 'info-border']);
const TEXT = check('foreground', ['fg', 'fg-muted', 'fg-subtle', 'fg-faint', 'accent', 'ember', 'ember-text', 'success-text', 'warning-text', 'danger-text', 'info-text']);

// Enumerated (non-token) scales.
const DISPLAY = ['flex', 'grid', 'block', 'inline-flex', 'inline-block', 'none'];
const DIRECTION = { row: 'row', col: 'column', 'row-reverse': 'row-reverse', 'col-reverse': 'column-reverse' };
const ALIGN = { start: 'flex-start', center: 'center', end: 'flex-end', stretch: 'stretch', baseline: 'baseline' };
const JUSTIFY = { start: 'flex-start', center: 'center', end: 'flex-end', between: 'space-between', around: 'space-around', evenly: 'space-evenly' };
const WRAP = { wrap: 'wrap', nowrap: 'nowrap', 'wrap-reverse': 'wrap-reverse' };
const SIZE = { full: '100%', auto: 'auto', fit: 'fit-content' };
const FLEX = { '1': '1 1 0%', auto: '1 1 auto', none: '0 0 auto' };
const COLUMNS = Array.from({ length: 12 }, (_, i) => String(i + 1));

// Spacing props → logical CSS property (RTL-first; pt/pb are block axis, ps/pe inline).
const SPACE_PROPS = {
  p: ['padding'],
  px: ['padding-inline'],
  py: ['padding-block'],
  pt: ['padding-block-start'],
  pb: ['padding-block-end'],
  ps: ['padding-inline-start'],
  pe: ['padding-inline-end'],
  gap: ['gap'],
  'gap-x': ['column-gap'],
  'gap-y': ['row-gap'],
};

// ── Emit CSS ────────────────────────────────────────────────────────────────
const L = []; // lines
L.push('/* GENERATED by scripts/gen-system.mjs — DO NOT EDIT.');
L.push(` * Atomic utilities for the typed <Box> layout vocabulary. Source: ${SOURCE}.`);
L.push(' * Logical properties throughout (RTL-first). Re-run: npm run gen:system. */');
L.push('');
const rule = (cls, body) => L.push(`.${cls}{${body}}`);

L.push('/* spacing (logical) */');
for (const [prop, props] of Object.entries(SPACE_PROPS))
  for (const t of SPACE) rule(`eb-${prop}-${t}`, props.map((p) => `${p}:var(--space-${t})`).join(';'));

L.push('/* radius */');
for (const t of RADIUS) rule(`eb-r-${t}`, `border-radius:var(--radius-${t})`);

L.push('/* color: background / border / foreground */');
for (const t of BG) rule(`eb-bg-${t}`, `background-color:var(--${t})`);
for (const t of BORDER) rule(`eb-bd-${t}`, `border:1px solid var(--${t})`);
for (const t of TEXT) rule(`eb-fg-${t}`, `color:var(--${t})`);

L.push('/* display */');
for (const t of DISPLAY) rule(`eb-d-${t}`, `display:${t}`);

L.push('/* flexbox */');
for (const [k, v] of Object.entries(DIRECTION)) rule(`eb-fd-${k}`, `flex-direction:${v}`);
for (const [k, v] of Object.entries(ALIGN)) rule(`eb-ai-${k}`, `align-items:${v}`);
for (const [k, v] of Object.entries(JUSTIFY)) rule(`eb-jc-${k}`, `justify-content:${v}`);
for (const [k, v] of Object.entries(WRAP)) rule(`eb-fw-${k}`, `flex-wrap:${v}`);
for (const [k, v] of Object.entries(FLEX)) rule(`eb-flex-${k}`, `flex:${v}`);

L.push('/* grid */');
for (const n of COLUMNS) rule(`eb-gc-${n}`, `grid-template-columns:repeat(${n},minmax(0,1fr))`);

L.push('/* sizing */');
for (const [k, v] of Object.entries(SIZE)) { rule(`eb-w-${k}`, `inline-size:${v}`); rule(`eb-h-${k}`, `block-size:${v}`); }

const cssOut = L.join('\n') + '\n';

// ── Emit TS token unions ──────────────────────────────────────────────────────
const arr = (name, vals) => `export const ${name} = [${vals.map((v) => `'${v}'`).join(', ')}] as const;`;
const union = (typeName, constName) => `export type ${typeName} = (typeof ${constName})[number];`;
const T = [];
T.push('// GENERATED by scripts/gen-system.mjs — DO NOT EDIT.');
T.push(`// Typed token vocabularies for the <Box> layout primitive. Source: ${SOURCE}.`);
T.push('// A value outside these unions is not expressible — it fails to compile.');
T.push('');
T.push(arr('SPACE_TOKENS', SPACE)); T.push(union('SpaceToken', 'SPACE_TOKENS')); T.push('');
T.push(arr('RADIUS_TOKENS', RADIUS)); T.push(union('RadiusToken', 'RADIUS_TOKENS')); T.push('');
T.push(arr('BACKGROUND_TOKENS', BG)); T.push(union('BackgroundToken', 'BACKGROUND_TOKENS')); T.push('');
T.push(arr('BORDER_TOKENS', BORDER)); T.push(union('BorderToken', 'BORDER_TOKENS')); T.push('');
T.push(arr('TEXT_TOKENS', TEXT)); T.push(union('TextToken', 'TEXT_TOKENS')); T.push('');
T.push(arr('DISPLAY_VALUES', DISPLAY)); T.push(union('Display', 'DISPLAY_VALUES')); T.push('');
T.push(arr('DIRECTION_VALUES', Object.keys(DIRECTION))); T.push(union('Direction', 'DIRECTION_VALUES')); T.push('');
T.push(arr('ALIGN_VALUES', Object.keys(ALIGN))); T.push(union('Align', 'ALIGN_VALUES')); T.push('');
T.push(arr('JUSTIFY_VALUES', Object.keys(JUSTIFY))); T.push(union('Justify', 'JUSTIFY_VALUES')); T.push('');
T.push(arr('WRAP_VALUES', Object.keys(WRAP))); T.push(union('Wrap', 'WRAP_VALUES')); T.push('');
T.push(arr('SIZE_VALUES', Object.keys(SIZE))); T.push(union('Size', 'SIZE_VALUES')); T.push('');
T.push(arr('FLEX_VALUES', Object.keys(FLEX))); T.push(union('FlexValue', 'FLEX_VALUES')); T.push('');
T.push(arr('COLUMN_VALUES', COLUMNS)); T.push(union('GridColumns', 'COLUMN_VALUES')); T.push('');
const tsOut = T.join('\n');

// ── Write / check ─────────────────────────────────────────────────────────────
const CSS_OUT = 'packages/ui/styles/system.gen.css';
const TS_OUT = 'packages/ui/src/system/tokens.gen.ts';

if (process.argv.includes('--check')) {
  let stale = false;
  for (const [path, next] of [[CSS_OUT, cssOut], [TS_OUT, tsOut]]) {
    const prev = existsSync(path) ? readFileSync(path, 'utf8') : '';
    if (prev !== next) { console.error(`✘ ${path} is stale — run \`npm run gen:system\` and commit.`); stale = true; }
  }
  if (stale) process.exit(1);
  console.log('✔ system layer in sync with token source.');
  process.exit(0);
}

writeFileSync(CSS_OUT, cssOut);
writeFileSync(TS_OUT, tsOut);
console.log(`Wrote ${CSS_OUT} (${cssOut.split('\n').filter((l) => l.startsWith('.')).length} classes) and ${TS_OUT}.`);
console.log(`  space:${SPACE.length} radius:${RADIUS.length} bg:${BG.length} border:${BORDER.length} text:${TEXT.length}`);
