// Generates src/lib/nav.ts (typed navigation tree) from nav-config.js + design-systems.js.
//
// Multi-DS: every nav item is tagged with its `ds` (via GROUP_DS). The Sidebar renders
// NAV_BY_DS[activeDs]; the switcher reads DESIGN_SYSTEMS. Core lives at flat routes
// (/<slug>); sub-DSs are navigated to via their `home` (routed prefixes land later).
// Re-run after editing nav-config.js or design-systems.js: `node scripts/gen-nav.mjs`.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const win = {};
new Function('window', readFileSync(resolve(root, 'src/ds/core/nav-config.js'), 'utf8'))(win);
new Function('window', readFileSync(resolve(root, 'src/ds/core/design-systems.js'), 'utf8'))(win);
const S = win.SECTIONS;
const DS = win.DESIGN_SYSTEMS;
const GROUP_DS = win.GROUP_DS || {};
const DS_BY_ID = Object.fromEntries(DS.map((d) => [d.id, d]));

// Standalone IDP examples live apart at /example/<name>. A DS only gets its routed
// prefix once `migrated` is flipped — until then its pages stay at flat /<slug> routes,
// so the app keeps working mid-migration.
function href(item, ds) {
  if (item.external) {
    const name = item.href.replace(/^pages\/examples\//, '').replace(/\.html$/, '');
    return `/example/${name}`;
  }
  if (item.href === 'design-system.html') return '/';
  if (ds && ds.basePath && ds.migrated) return `/${ds.basePath}/${item.id}`;
  return `/${item.id}`;
}

const toItem = (it, ds) => {
  const o = { slug: it.id, label: it.label, href: href(it, ds), ds: ds.id };
  if (it.badge) o.badge = it.badge;
  if (it.external) o.external = true;
  return o;
};

// Sidebar items are sorted ALPHABETICALLY by label within each (sub)group, with the
// DS landing ("overview") pinned first. "Get Started" keeps its authored pedagogical
// order (Introduction → Installation → …).
const PIN_FIRST = ['overview'];
const NO_SORT = new Set(['Get Started']);
const sortItems = (items, group) => {
  if (NO_SORT.has(group)) return items;
  const pinned = items.filter((it) => PIN_FIRST.includes(it.slug));
  const rest = items.filter((it) => !PIN_FIRST.includes(it.slug)).sort((a, b) => a.label.localeCompare(b.label));
  return [...pinned, ...rest];
};

const groups = S.groups.map((g) => {
  const ds = DS_BY_ID[g.ds || GROUP_DS[g.group] || 'core'];
  if (g.subgroups) {
    return {
      group: g.group,
      ds: ds.id,
      subgroups: g.subgroups.map((sg) => ({ subgroup: sg.subgroup, items: sortItems(sg.items.map((it) => toItem(it, ds)), g.group) })),
    };
  }
  return { group: g.group, ds: ds.id, items: sortItems(g.items.map((it) => toItem(it, ds)), g.group) };
});

const out = `// AUTO-GENERATED by scripts/gen-nav.mjs — do not edit by hand.
// Typed navigation tree + Design System family (source: nav-config.js + design-systems.js).
/* eslint-disable */
export type DesignSystemId = ${DS.map((d) => JSON.stringify(d.id)).join(' | ')};
export type DesignSystem = { id: DesignSystemId; label: string; tagline: string; basePath: string; icon: string; home: string; migrated: boolean };
export type NavItem = { slug: string; label: string; href: string; ds: DesignSystemId; badge?: string; external?: boolean };
export type NavGroup = {
  group: string;
  ds: DesignSystemId;
  items?: NavItem[];
  subgroups?: { subgroup: string; items: NavItem[] }[];
};

export const NAV_VERSION = ${JSON.stringify(win.EIDOS_VERSION || '1.8.0')};

/** The ordered family of Design Systems. \`core\` is the shared base. */
export const DESIGN_SYSTEMS: DesignSystem[] = ${JSON.stringify(DS, null, 2)};

/** Every nav group, each tagged with the DS it belongs to. */
export const NAV: NavGroup[] = ${JSON.stringify(groups, null, 2)};

/** Groups scoped per Design System (what the Sidebar renders for the active DS). */
export const NAV_BY_DS: Record<DesignSystemId, NavGroup[]> = DESIGN_SYSTEMS.reduce(
  (acc, ds) => { acc[ds.id] = NAV.filter((g) => g.ds === ds.id); return acc; },
  {} as Record<DesignSystemId, NavGroup[]>,
);

/** Flat list of every leaf item (with its group + subgroup + ds). */
export const NAV_FLAT: (NavItem & { group: string; subgroup?: string })[] = NAV.flatMap((g) =>
  g.subgroups
    ? g.subgroups.flatMap((sg) => sg.items.map((it) => ({ ...it, group: g.group, subgroup: sg.subgroup })))
    : (g.items ?? []).map((it) => ({ ...it, group: g.group })),
);

/** The home href for a DS ('' slug → root; routed prefix only once migrated). */
export function dsHref(ds: DesignSystem): string {
  if (ds.basePath) return ds.migrated ? \`/\${ds.basePath}/\${ds.home}\` : \`/\${ds.home}\`;
  return ds.home ? \`/\${ds.home}\` : '/';
}

/** Resolve the active item + its DS + breadcrumb trail for a pathname. */
export function navForPath(pathname: string) {
  const item = NAV_FLAT.find((i) => i.href === pathname) ?? null;
  const ds = (item?.ds ?? 'core') as DesignSystemId;
  const trail = item ? [item.group, item.subgroup, item.label].filter(Boolean) as string[] : [];
  return { item, ds, trail };
}
`;

writeFileSync(resolve(root, 'src/lib/nav.ts'), out);
console.log(`Wrote src/lib/nav.ts (${DS.length} design systems, ${groups.length} groups, ${out.split('slug:').length - 1} items).`);
