import * as React from 'react';
import { AILabel } from '@/components/forge/ai-label';

const AILabelWithPopover = ({
  variant = 'pill',
  size = 'md',
  label = 'AI summary',
  model = 'eidos-ai/gpt-4o-mini',
  ts = '2 min ago',
  confidence = 0.92,
  children,
}: {
  /** Trigger flavor — see AILabel variants. */
  variant?: 'box' | 'mark' | 'pill' | 'dot';
  /** Scale of the trigger badge. */
  size?: 'sm' | 'md' | 'lg';
  /** Title shown at the top of the popover. */
  label?: string;
  /** Model identifier. Mono-rendered in the metadata row. */
  model?: string;
  /** When the AI value was produced. Free-form string ("2 min ago", "2024-11-04"). */
  ts?: string;
  /** Confidence score 0–1. Rendered as a percentage in the popover. */
  confidence?: number;
  /** Short description shown in the popover body. */
  children?: React.ReactNode;
}) => {
  const desc = children || 'This value was generated by an AI model.';

  const [open, setOpen] = React.useState(false);
  const ref = React.useRef<HTMLSpanElement>(null);

  React.useEffect(() => {
    if (!open) return;
    const onDoc = (e: MouseEvent) => { if (ref.current && !ref.current.contains(e.target as Node)) setOpen(false); };
    const onKey = (e: KeyboardEvent) => { if (e.key === 'Escape') setOpen(false); };
    document.addEventListener('mousedown', onDoc);
    document.addEventListener('keydown', onKey);
    return () => {
      document.removeEventListener('mousedown', onDoc);
      document.removeEventListener('keydown', onKey);
    };
  }, [open]);

  return (
    <span className="ai-pop-anchor" ref={ref}>
      <AILabel variant={variant} size={size} interactive onClick={() => setOpen(!open)}>AI</AILabel>
      {open ? (
        <div className="ai-pop" role="dialog" aria-label="AI source">
          <div className="ai-pop-head">
            <AILabel variant="box" size="sm"/>
            <span>{label}</span>
          </div>
          <p className="ai-pop-desc">{desc}</p>
          <dl className="ai-pop-meta">
            <dt>Model</dt><dd>{model}</dd>
            <dt>When</dt><dd>{ts}</dd>
            <dt>Confidence</dt><dd>{Math.round(confidence * 100) + '%'}</dd>
          </dl>
          <div className="ai-pop-actions">
            <button className="btn xs ember">Accept</button>
            <button className="btn xs ghost">Edit</button>
            <button className="btn xs ghost" onClick={() => setOpen(false)}>Revoke</button>
          </div>
        </div>
      ) : null}
    </span>
  );
};

export { AILabelWithPopover };
