'use client';
import { ChangelogView, type ChangelogEntry } from '@/components/docs';

// ─── Source of truth ────────────────────────────────────────────────────
// Newest first. Group by version; if a single version touched several
// components, list one entry per scope so search can pinpoint changes.
const CHANGELOG: ChangelogEntry[] = [
  // ─── v1.15.0 — Catalog-wide design-critique remediation (2026-05-31) ──────
  { version: 'v1.15.0', date: '2026-05-31', type: 'fix', scope: 'core', title: 'Design-critique remediation across all 217 doc pages',
    summary: 'A full design audit (every doc page + every Storybook story) drove a fix program closed against eidos:verify (0 block-fail) + headless render. 11 P0 corrected: contrast on the Color ember-scale, Severity tiles, Textarea counter and mobile Snackbar — now token-driven and AA in both themes; emoji slop removed from Response/Pagination; status.tsx’s page-local CSS block promoted into ds.css. The single ember-on-fill invariant and the ≤220-char lede budget hold catalog-wide.' },
  { version: 'v1.15.0', date: '2026-05-31', type: 'feat', scope: 'core', title: 'Doc↔code a11y/motion sync — documented behaviour implemented, not just described',
    summary: '~130 "docs claim X, component does Y" mismatches closed by IMPLEMENTING the documented behaviour in @eidos/ui (never by deleting the promise): LogViewer body gained real keyboard panning (arrows/PageUp/Down/Home/End) + role="log" + aria-live + a focus ring; mobile Checkbox rows regained their focus-visible ring; severity-chip aria-pressed, prefers-reduced-motion guards and missing ARIA wired across AI/IDP/mobile components. The few cases where implementing would change a shipped contract had their docs corrected to the truth instead.' },
  { version: 'v1.15.0', date: '2026-05-31', type: 'tokens', scope: 'core', title: 'New tokens — --ink-fixed, --snackbar-bg/-fg, --severity-p{0..3}-ink, --tnum',
    summary: '--ink-fixed: a theme-independent dark ink for foregrounds on hardcoded bright fills (unlike --ember-fg it never flips to white). --snackbar-bg / --snackbar-fg: a fixed dark inverse surface so the snackbar’s single ember action keeps AA in both themes. --severity-p{0..3}-ink: per-tile ink that follows the tile’s own luminance (fixes white-on-amber P2). --tnum: tabular-nums alias for metric numerics.' },
  { version: 'v1.15.0', date: '2026-05-31', type: 'docs', scope: 'core', title: 'Storybook coverage — 156 stories added across 40 components',
    summary: 'Thin and misfiled stories brought to the CSF3 standard: a Default + one story per documented variant/size/state + an InContext, with the correct Group taxonomy. The pass also surfaced (and flagged, not forced) real binding gaps — Conversation/History props the component ignores, and documented-but-unexported subcomponents — captured in docs/CRITIQUE-FOLLOWUPS.md.' },
  { version: 'v1.15.0', date: '2026-05-31', type: 'docs', scope: 'core', title: 'Craft elevation pass — Detail / Function / a11y lifted catalog-wide',
    summary: 'A per-page craft pass (off-scale fontSize → the fixed type scale, tabular-nums on metrics, real empty/loading/error coverage, true keyboard/ARIA/contrast/reduced-motion, single-accent discipline) plus earned signature interactions where the surface warranted one — a deep-linkable FAQ Accordion, a travelling reasoning cursor on Chain-of-thought, a working Checkpoint rewind, a live Persona state-cycle, reduced-motion-gated chart growth. Per-DS averages now ≈ Philosophy 8.2 / Hierarchy 8.0 / Function 8.0 / Detail 7.3 / Innovation 7.3. Deferred follow-ups tracked in docs/CRITIQUE-FOLLOWUPS.md.' },
  { version: 'v1.15.0', date: '2026-05-31', type: 'fix', scope: 'core', title: 'Version badge synced to v1.15.0 (core) in sidebar + topbar',
    summary: 'DS_VERSIONS.core bumped to 1.15.0 in src/lib/site.ts; the DS-aware VersionBadge picks it up on the core surface.' },

  // ─── v1.14.0 — Atomic Pill/Chip/Badge + Avatar rebuild + photos (2026-05-30) ──────
  { version: 'v1.14.0', date: '2026-05-30', type: 'feat', scope: 'avatars', title: 'Avatar rebuilt to a full identity API + photo support',
    summary: 'Avatar gained size presets (xs-xl), a src image with deterministic initials fallback, a presence status dot (online/away/busy/offline; 2px ring; logical-property placement so it mirrors in RTL), and <Avatar.Group> for overlapping team rows with a +N overflow — while keeping the legacy { p } API working for existing callers. OwnerPill now accepts a photo (person.src) and hugs its content instead of stretching the row. Seven optimized headshots ship in public/avatars for photo examples, with matching Storybook stories.' },
  { version: 'v1.14.0', date: '2026-05-30', type: 'feat', scope: 'pills', title: 'Pill / Chip / Badge split into atomic pages',
    summary: 'The old "Pills & Chips" page was repartitioned: Chip now has its own page, Pill is Pill-only, Badge keeps its own page — each with full anatomy, Accessibility, RTL, and a generated <AutoPropsTable>, matching the per-component install model (eidos add pill | chip | badge). Cross-links keep the family discoverable.' },
  { version: 'v1.14.0', date: '2026-05-30', type: 'docs', scope: 'shell', title: 'Sidebar + Storybook ordered alphabetically',
    summary: 'Nav items now sort A-Z within each section (Get Started keeps its pedagogical order; each DS landing is pinned first), and Storybook sorts stories alphabetically within each group.' },

  // ─── v1.13.0 — Deterministic contract harness + consolidation (2026-05-29) ──────
  { version: 'v1.13.0', date: '2026-05-30', type: 'feat', scope: 'core', title: 'Deterministic contract harness — npm run eidos:verify',
    summary: 'A single machine-readable eidos.contract.json defines "a component is Done" across its four surfaces (docs page, @eidos/ui export, Storybook story, registry item). eidos:verify aggregates every check — a11y, headless render, nav integrity, frame-code, visual regression, 4-surface parity, section structure, story coverage, registry validity — into per-component clause results, applies reviewed waivers, and renders a generated EIDOS-HEALTH.md wall. New PreToolUse + Stop hooks gate edits against the contract.' },
  { version: 'v1.13.0', date: '2026-05-29', type: 'feat', scope: 'core', title: 'Component consolidation + generated API tables',
    summary: 'The Pill/Chip/Badge trio was unified, Calendar gained a single selectionMode, CountUp/Counter de-duplicated, and Select rebuilt as a custom dropdown. API reference tables are now generated from the typed component props (<AutoPropsTable> backed by props.generated), so they can no longer drift from the source; the core components were typed and JSDoc-documented to feed them.' },

  // ─── v1.12.0 — Monorepo extraction + Next 16 / React 19 (2026-05-26) ──────
  { version: 'v1.12.0', date: '2026-05-26', type: 'feat', scope: 'core', title: 'Extracted to a Turborepo monorepo + source-shipped distribution',
    summary: 'The component layer moved to the @eidos/ui package; a shadcn-schema @eidos/registry plus the eidos CLI copy components straight into a consuming repo (source-shipped — you own the code, not a locked dependency); @eidos/storybook hosts the isolated component workbench. Design tokens export to the W3C DTCG format (tokens/forge.tokens.json).' },
  { version: 'v1.12.0', date: '2026-05-26', type: 'feat', scope: 'core', title: 'Next.js 14 to 16 + React 18 to 19',
    summary: 'Upgraded to Next 16 (Turbopack is now the default builder) and React 19. The async Request APIs (params is now a Promise) were applied to the dynamic routes; recharts moved to 2.15.x for the React 19 peer range. Build green across every route.' },

  // ─── v1.11.0 — Page typography primitives + RTL across all components (2026-05-22) ──────
  { version: 'v1.11.0', date: '2026-05-22', type: 'feat', scope: 'core', title: 'Shared <Lede> / <Mono> page-prose primitives',
    summary: 'Section intros and inline code refs are now two exported primitives — <Lede> (the muted 64ch --text-sm explainer, unified onto .ds-caption) and <Mono> (ember inline code) — so pages stop hand-rolling font sizes. docs/DS-PAGE-STANDARD.md §3.5 codifies the type scale against the --text-* tokens and §3.6 makes the RTL section required; the component-page / new-component / new-page / ds-component-authoring skills and the release flow were rewritten to the current migrated-TSX architecture (no more window.PAGES / shell.jsx / gen-manifest).' },
  { version: 'v1.11.0', date: '2026-05-22', type: 'docs', scope: 'core', title: 'RTL section added to 20 core components',
    summary: 'Every core component doc page that lacked one now ships the required RTL section — a live dir="rtl" preview plus a Lede naming exactly what mirrors and what stays. The Sidebar docks to the right, Menubar/Resizable reverse pane/menu order, Scroll Area moves its bar to the inline-start (left) edge, Command/Banner/Badge flip their icon areas; direction-agnostic primitives (Count up, Kbd, Relative time, Separator, Surfaces, Trend) say so honestly. Foundations/Get-Started pages are exempt per the foundation template.' },

  // ─── v1.10.0 — Page standard + visual anatomy + role-set tokens (2026-05-22) ──────
  { version: 'v1.10.0', date: '2026-05-22', type: 'docs', scope: 'core', title: 'Page-section standard rolled out across all 148 pages',
    summary: 'Approved docs/DS-PAGE-STANDARD.md (canonical section anatomy + vocabulary) and applied it to every doc page in every DS. Each page got a sharpened, professional page-header lede and a required Accessibility section (component-specific Keyboard / Screen reader / Focus & contrast / Motion) — coverage went from ~4 pages to 141. Charts gained Anatomy; the thin Blocks (cta-banner / feature-grid / split-feature / stat-band) and all Mobile component pages were fleshed out to the full template (Usage → Anatomy → Accessibility → Do/Don\'t → Spec).' },
  { version: 'v1.10.0', date: '2026-05-22', type: 'docs', scope: 'core', title: 'Visual anatomy everywhere',
    summary: 'Converted the remaining 27 prose anatomy blocks (Charts, Mobile, Blocks) to the gold-standard visual pattern: the real component rendered in a stage with numbered pins on each part (dashed connectors) and a numbered legend below — matching the Buttons reference. All 101 anatomy sections now read the same.' },
  { version: 'v1.10.0', date: '2026-05-22', type: 'feat', scope: 'foundations', title: 'Color page — info role + relocations',
    summary: 'The Color page now documents the info role set (sky; --info-text = --ice) with live swatches and adds info pairs to the contrast table. Two domain sections left Core: the data-viz palette moved to /charts/colors, and the severity / run-status / health / risk palettes now point to their canonical /severity + /status pages instead of duplicating them inline. Core color keeps surfaces, foreground, ember, info, and the generic status trio.' },
  { version: 'v1.10.0', date: '2026-05-22', type: 'tokens', scope: 'core', title: 'Semantic colour role-set + info role',
    summary: 'Implemented the approved colour model (docs/COLOR-SYSTEM-PROPOSAL.md §4): every functional role — ember, info, success, warning, danger — now exposes the same 7-token contract (--{r} / -strong / -soft / -subtle / -border / -text / -fg), with info promoted to a first-class role (sky; --info-text aliases --ice). Dark + light, fully additive — existing tokens keep their meaning (--ember-fg / --danger-fg unchanged), nothing repurposed. Color-page docs + data-viz/IDP relocation are the next step.' },
  { version: 'v1.10.0', date: '2026-05-22', type: 'feat', scope: 'docs', title: 'Content width + TOC alignment normalised',
    summary: 'One global --ds-content-w (940px) drives the content column on every page, with or without the "On this page" rail, so widths match across the family. The rail layout uses symmetric outer margins (equal left/right) with a capped content↔rail gap, so the guide never leaves dead space on the right.' },

  // ─── v1.9.0 — Multi-DS family + doc hierarchy (2026-05-21) ──────
  { version: 'v1.9.0', date: '2026-05-21', type: 'breaking', scope: 'core', title: 'Eidos split into a multi-DS family — core + 6 sub-DSs',
    summary: 'Eidos is now a family: the core DS at the root (Introduction, Foundations, Components) plus six route-prefixed sub-DSs — Charts (/charts), AI (/ai), IDP (/idp), Blocks (/blocks), Patterns (/patterns), Mobile (/mobile). Each sub-DS inherits the same tokens, primitives and ember accent (the core is the base) and adds its own surfaces. The sidebar header is now a DS switcher; nav is generated per-DS (NAV_BY_DS) and the active DS is derived from the route. Migration was incremental via a per-DS `migrated` flag so the app never broke between steps.' },
  { version: 'v1.9.0', date: '2026-05-21', type: 'feat', scope: 'core', title: 'window-registry bridge cut — SWC re-enabled',
    summary: 'The legacy window-registry bridge (install-globals + generated manifest) is gone; core modules are plain ES modules and migrated pages import from @/ds/core. .babelrc removed so Next compiles with SWC again; package.json marks sideEffects: ["*.css"] so the core barrel tree-shakes (recharts only ships in chart chunks). 178 statically-generated routes.' },
  { version: 'v1.9.0', date: '2026-05-21', type: 'feat', scope: 'docs', title: 'Text hierarchy rebuilt — semantic H2 section headings + floating "On this page" rail',
    summary: 'SubHead now renders a semantic <h2> at 22px (was a 13px <div>), closing the old 40px→13px jump so sections read as sections across all ~1244 headings + 149 pages in one change. A floating "On this page" TOC (right rail, scroll-spy) is generated from those headings on wide screens; the two competing H1 systems were unified.' },
  { version: 'v1.9.0', date: '2026-05-21', type: 'feat', scope: 'docs', title: 'Two doc layouts — content always centered',
    summary: 'Pages without sections (Introduction, every sub-DS Overview) render a single centered column; pages with sections render centered content + the floating TOC rail (≥1536px). The content column never sits off-center against the rail.' },
  { version: 'v1.9.0', date: '2026-05-21', type: 'feat', scope: 'shell', title: 'Sidebar DS switcher + header refinements',
    summary: 'The sidebar header became a DS switcher (ember tile + name + tagline + a dropdown of all DSs). Removed the avatar + notification bell; version is a badge; the theme toggle is a compact segmented pill; the topbar back button is gone. The ForgeMark fills with --bg so it flips with the theme.' },
  { version: 'v1.9.0', date: '2026-05-21', type: 'feat', scope: 'overview', title: 'Sub-DS Overviews — Introduction-style, domain heroes',
    summary: 'Every sub-DS now opens with an Introduction-style Overview (eyebrow · title · subtitle · lede · hero · principles · start-here · footer) via a shared DsOverview layout. The hero’s right column is domain-specific: Charts shows real charts, AI a live streaming chat, IDP a service card + deploy pipeline, Patterns texture swatches, Blocks a section preview, Mobile a DeviceFrame bleeding to the hero’s edge.' },
  { version: 'v1.9.0', date: '2026-05-21', type: 'fix', scope: 'core', title: 'Section eyebrow resolves by route',
    summary: 'The page-header eyebrow matched its nav item by id-slug, which is ambiguous across DSs (every DS has an "overview"). It now resolves by the current pathname, so sub-DS pages show their real group ("Charts"/"AI"/…) instead of falling back to "Eidos".' },
  { version: 'v1.9.0', date: '2026-05-21', type: 'feat', scope: 'changelog', title: 'Per-DS changelogs',
    summary: 'Each sub-DS now has its own Changelog, identical in structure to this one (shared ChangelogView component), scoped to that DS’s own history.' },

  // ─── v1.8.1 — Component polish + visual refinements (2026-05-17) ──────
  { version: 'v1.8.1', date: '2026-05-17', type: 'feat',    scope: 'service-card',  title: 'ServiceCard fully rebuilt to a 3-variant recipe',
    summary: 'Rewritten from scratch after the catalog page revealed three structural problems: TierBadge in the top-right read as a static classification when the user actually scans for health; OwnerPill spilled to a second line on narrow grid cells; "Last deploy" timestamp ran past the right edge. The new component has compact / default / detailed variants and a footer driven by a 2-column grid (minmax(0,1fr) + auto) so contents truncate predictably. Top-right slot moved from TierBadge to HealthBadge (with pulse on degraded). Header micro-label now stacks "v2.7.0 · 14m ago" so version + deploy live on one mono line. Footer left switched from a single OwnerPill to an AvatarGroup with up to 3 contributors + a "+N" tile — same markup the Avatars page uses, so a catalog row reads as a team artifact. Footer right shows LangBadge (lang dot + name) so a grid reads its silhouette by colour at a glance.' },
  { version: 'v1.8.1', date: '2026-05-17', type: 'feat',    scope: 'agent-card',    title: 'AgentCard rebuilt to mirror the new catalog rhythm',
    summary: 'Same 4-band vertical rhythm as the new ServiceCard so a grid that mixes both reads as one surface. Header: 44px ember-soft avatar tile + name + model micro-label + HealthBadge flush right. Summary clamped to 2 lines so cards align in auto-fill grids regardless of summary length. Capability chips (max 4) + "+N" overflow. Footer: hairline-divided, inline stats ("1,247 runs · 96% success") + RelativeTime. Replaces the previous 3-column KV grid that competed with the title for attention.' },
  { version: 'v1.8.1', date: '2026-05-17', type: 'fix',     scope: 'service-card',  title: 'ServiceCard AvatarGroup matches the canonical Avatars page',
    summary: 'Earlier iteration rendered contributors via the Avatar atom at size 24 with a custom .avatar-more modifier on the overflow tile. The Avatars page documents a different (and simpler) pattern: plain <span className="avatar">{initials}</span> with the same default chrome for the +N tile. ServiceCard now renders the same way — no custom modifier, no size override. The tile inherits --bg-elevated background, --border-strong border, mono 10.5px font from the canonical .avatar class.' },
  { version: 'v1.8.1', date: '2026-05-17', type: 'feat',    scope: 'resizable',     title: 'Resizable rebuilt — handles work on both axes, divider readable in dark',
    summary: 'The old component had a 1px line at --border (6% on dark) that disappeared into the surface, and the vertical split had no drag handler — it only rendered a static divider. New version uses shared VerticalLine / HorizontalLine / GripPill primitives with a 10px transparent hit zone, 1px --border-strong line (12% / 14% slate), grip pill on --surface-overlay with --elev-1. Both axes carry pointer-down drag handlers with clamps. ARIA: role="separator" + aria-orientation + aria-valuenow/min/max. The hit zone gets background: var(--surface) so the body tone doesn\'t bleed through the dragable area.' },
  { version: 'v1.8.1', date: '2026-05-17', type: 'fix',     scope: 'charts',        title: 'Radar polar grid soft — driven by props, no !important',
    summary: 'The outermost ring of every radar chart was rendering at the Recharts default stroke (heavier than the inner concentric rings), so the hexagon outline read as a hard frame. Fix: dropped every per-chart CSS rule for .recharts-polar-grid-* and pass a single gridProps object to every <PolarGrid> on the page: stroke=var(--fg) at 14% alpha, strokeDasharray="3 4", strokeWidth=1. Component props beat the Recharts defaults via natural cascade, no !important needed. Every ring (inner + outermost) now renders identically as soft dashed hairlines.' },
  { version: 'v1.8.1', date: '2026-05-17', type: 'feat',    scope: 'charts',        title: 'Chart tooltip restyled — bigger label, larger dot, calmer typography',
    summary: 'Header label switched from uppercase mono micro-label (--fg-faint) to sentence-case --fg semibold at --text-md. Series row dot grew from 8px circle to 12px rounded square (matches the chart legend swatch style). Series name uses --fg-muted at --text-base; value is --fg semibold tabular-nums at the same size. Row gap 4→6px, column gap 8→10px so adjacent series breathe.' },
  { version: 'v1.8.1', date: '2026-05-17', type: 'tokens',  scope: 'core',          title: 'Elevation — Fluent-style 2-shadow ramp',
    summary: 'Refactored --elev-1..4 to compose a sharp key shadow + a low-spread ambient. Low ramp (elev-1, elev-2) keeps ambient on the same (0, n/2, n) axis as the key for a tight, quiet lift. High ramp (elev-3, elev-4) swaps ambient for a (0, 0, blur) contact halo so floating layers (popover / modal / sheet) read as genuinely above the page. Removed the inset-highlight bevel from dark mode entirely — surface tone does the lifting; the highlight was competing with the natural lighter tone of the surface tier above.' },
  { version: 'v1.8.1', date: '2026-05-17', type: 'fix',     scope: 'severity',      title: 'Severity light mode — brighter hues so P1/P2/P3 read distinct',
    summary: 'Earlier light values mapped to deep neutrals (P1 #C2410C, P2 #B45309, P3 #0369A1) which felt mustard / muddy. Bumped to: P1 #EA580C (orange-500), P2 #EAB308 (yellow-500), P3 #0EA5E9 (sky-500). P0 stays #B91C1C (deeper red signals critical without ever competing for attention). Severity-p2 pill text drops to #854D0E in light mode so yellow-on-yellow soft (#EAB308 @18%) stays AA-readable; the solid swatch keeps the bright value.' },
  { version: 'v1.8.1', date: '2026-05-17', type: 'fix',     scope: 'sidebar',       title: 'Active nav item — neutral foreground, surface-active background',
    summary: '.ds-link.active and .nav-item.active dropped the ember text colour — the left rail + bold weight + surface-active tone already mark the page; ember text was distracting. Both selectors stay in sync. surface-active in dark mode is the lightest tier (oklch 0.32) so the row clearly lifts above the rest of the nav.' },
  { version: 'v1.8.1', date: '2026-05-17', type: 'fix',     scope: 'frame',         title: 'Frame chrome — canonical 3-surface assignment',
    summary: 'Frame now always renders with three distinct surface tones in both themes: header = --surface, body = --bg-elevated, code well = --bg. The collapsible "Show code" wrapper (.ds-code-collapse) inherits the code-well background so long snippets don\'t drift back to body tone when revealed. Removed every [data-mode="light"] override on Frame internals — single source of truth in the surface ladder.' },
  { version: 'v1.8.1', date: '2026-05-17', type: 'fix',     scope: 'spacing',       title: 'Spacing scale page — column gap and bar room',
    summary: 'The 96px max bar in the spacing scale touched the description cell because the bar column was fixed at 80px. Bumped to 110px, grid gap 16 → 24, paddingInlineStart: 8 on the description so each row of the scale breathes.' },
  { version: 'v1.8.1', date: '2026-05-17', type: 'fix',     scope: 'core',          title: 'Version badge synced to v1.8.1 in sidebar + topbar',
    summary: 'Sidebar sub-text ("Design System v1.8.1") and topbar pill ("v1.8.1 · Stable") updated in shell.jsx — they always stay in sync.' },

  // ─── v1.8.0 — Color system + elevation rebuild (2026-05-17) ──────
  { version: 'v1.8.0', date: '2026-05-17', type: 'tokens',   scope: 'core',         title: 'Surface ladder rewritten in OKLCH — 7 tiers, monotonic, warm undertone',
    summary: 'The previous palette anchored the canvas at #08090A (essentially pure black) and capped the elevation ladder before it could express depth. The new system uses OKLCH with a subtle warm undertone (hue ~60°, chroma 0.003). 7 semantic tiers in each theme — --canvas (deepest, behind floating layers), --bg (page), --bg-elevated (topbar/sidebar/code well), --surface (default card), --surface-hover, --surface-overlay (floating layers), --surface-active (selected/pressed). Wider tier gaps (~0.04 ΔL) so stacked elements stay distinguishable even three or four levels deep. Light mode mirrors the logic: deepest is a warm tinted grey, --surface is pure white. Back-compat aliases (--surface-base/--surface-canvas/--surface-sunken/--surface-raised) preserved for existing component pages.' },
  { version: 'v1.8.0', date: '2026-05-17', type: 'tokens',   scope: 'core',         title: 'Elevation rebuilt as Fluent-style 2-shadow ramp',
    summary: 'Old --shadow-* tokens replaced by --elev-0..4 + --elev-ember. Each tier composes Shadow-1 (key, 0 Y=n/2 blur=n) + Shadow-2 (ambient). Low ramp (elev-1, elev-2) keeps ambient on the same axis for a quiet lift; high ramp (elev-3, elev-4) swaps ambient for a tight (0,0,blur) contact halo so the element reads as truly floating. Removed the inset-highlight bevel from dark mode — surface tone now does the lifting instead. --shadow-* tokens kept as aliases to --elev-*.' },
  { version: 'v1.8.0', date: '2026-05-17', type: 'tokens',   scope: 'core',         title: '--ember-fg / --danger-fg tokens — primary foreground',
    summary: 'The text colour that rides on top of var(--ember) / var(--danger) backgrounds is now theme-aware: dark text on bright accent in dark mode, white text on the deeper accent in light mode. .btn.ember, .btn.destructive, calendar selected day, date-picker range, table checkbox, input-group ember button, modal destructive button, avatar bubbles in hover-card / sidebar / linear-grid, AI conversation badge, AI prompt-input send button, service-scaffold check icon, ai-cite-chip hover, ai-hist-new pill — all migrated to var(--ember-fg) / var(--danger-fg). No more #08090A or #FFFFFF hardcoded on primary surfaces.' },
  { version: 'v1.8.0', date: '2026-05-17', type: 'tokens',   scope: 'severity',     title: 'Severity scale rebalanced — luminance-tuned per theme',
    summary: 'Dark mode P0 #DC2626 → #FB5252 (brighter red so "critical" lands against the deep surface), P1 #F97316 → #FB923C, soft alphas 14% → 18%. Light mode tuned for hue legibility on white: P0 #B91C1C, P1 #EA580C (orange-500), P2 #EAB308 (yellow-500), P3 #0EA5E9 (sky-500). Severity-p2 pill text falls to #854D0E in light mode so yellow-on-yellow-soft stays readable; the swatch keeps the bright value.' },
  { version: 'v1.8.0', date: '2026-05-17', type: 'tokens',   scope: 'core',         title: 'Frame chrome — 3 distinct surfaces',
    summary: '<Frame /> now always renders with three visibly distinct surfaces in both themes: header = --surface, body = --bg-elevated, code well = --bg. The collapsed-snippet wrapper (.ds-code-collapse) gets the same code-well background so long "Show code" reveals don\'t drift back to body tone. Light-mode hex overrides for code-toggle, fade gradient and toggle row removed — they all resolve through tokens now.' },
  { version: 'v1.8.0', date: '2026-05-17', type: 'tokens',   scope: 'borders',      title: '--border-subtle joins the hairline scale',
    summary: 'Four border tiers now: --border-subtle (4% alpha — barely-there row separators inside tables), --border (default hairline), --border-strong (interactive boundary, inputs), --border-stronger (focused / pressed). Same alpha progression in light mode using slate ink instead of white.' },
  { version: 'v1.8.0', date: '2026-05-17', type: 'feat',     scope: 'foundations',  title: 'Color page — Foreground on primary section + live swatches',
    summary: 'New SubHead "Foreground on primary" documents --ember-fg / --danger-fg with side-by-side dark/light hex audit and a Frame that flips with the theme. Surface scale, accents and status arrays now live-pull each swatch via var(--token), so the page is theme-aware — no more rendering only the dark values.' },
  { version: 'v1.8.0', date: '2026-05-17', type: 'feat',     scope: 'foundations',  title: 'Elevation page — Surfaces ladder cross-section + tiers-layered demo',
    summary: 'Foundations / Elevation renamed from "Shadows & Borders" and reorganised: single cross-section showing the 7 surface tones stacked (canvas marked between dashed "page line" rules, deepest tier offset below as "behind modals"), 5-tier nested-cards demo proving stacked depth works without shadows, single shadow grid (no more dark/light side-by-side comparisons — theme switcher does that). Anatomy moved to the canonical slot right before Do/Don\'t.' },
  { version: 'v1.8.0', date: '2026-05-17', type: 'feat',     scope: 'foundations',  title: 'Severity page — light/dark hex audit + theme-aware swatch column',
    summary: 'P0–P3 cards now show "dark · #FB5252 · light · #B91C1C" on each row, swatch column paints from var(--severity-p*) live, foreground uses --ember-fg. Caption explains the luminance-tuning principle.' },
  { version: 'v1.8.0', date: '2026-05-17', type: 'tokens',   scope: 'core',         title: 'Codemod — borderRadius + fontSize → tokens across 146 files',
    summary: '275 inline borderRadius values (3/4/5/6/8/12) substituted into var(--radius-xs..2xl); 1081 inline fontSize values (11/12.5/13/14/15/17/20/28/36) into var(--text-xs..3xl). Components, foundations, AI, charts, get-started, patterns, elements, resources, examples — all swept. Off-scale numbers (10.5, 13.5, 18) left as-is. A Tailwind config change to either scale now propagates to every page demo.' },
  { version: 'v1.8.0', date: '2026-05-17', type: 'tokens',   scope: 'core',         title: 'P0 sweep — 12 hand-rolled box-shadows migrated to --elev-*',
    summary: 'command.jsx, menubar.jsx, hover-card.jsx, navigation.jsx, sidesheet.jsx, drawer.jsx, tooltips.jsx, popover.jsx (CSS + JSX), ai-label.jsx, recharts tooltip — all "0 24px 64px rgba(0,0,0,0.45)…" style shadows replaced with var(--elev-3) or var(--elev-4). Light-mode shadows are now tinted slate-ink (not pure black) automatically. Light-mode .pop / .in-pop / .ai-cite-pop overrides removed — single-source-of-truth in the token.' },
  { version: 'v1.8.0', date: '2026-05-17', type: 'tokens',   scope: 'core',         title: 'Alias → canonical names on foundations docs pages',
    summary: 'foundations/shadows.jsx, foundations/color.jsx, components/surfaces.jsx — 51 references to --surface-base/--surface-canvas/--surface-sunken/--surface-raised and --shadow-N migrated to the canonical --surface/--bg/--bg-elevated/--surface-overlay/--elev-N names. The pages that document the surface system don\'t promote aliases anymore. Component pages keep the aliases as-is (back-compat).' },
  { version: 'v1.8.0', date: '2026-05-17', type: 'tokens',   scope: 'core',         title: 'ds.css stale light overrides → tokens',
    summary: '13 light-mode rules with hardcoded hex (#F6F6F7, #FAFAFA, #FFFFFF, rgba(0,0,0,X)) on .ds-codetree, .ds-tabs, .ds-props-table, .ds-code-toggle, .scale-bar — all converted to var(--surface) / var(--bg-elevated) / var(--bg) / var(--border) / var(--fg). Syntax-highlighting hex kept (those need explicit AA-tuned colours).' },
  { version: 'v1.8.0', date: '2026-05-17', type: 'fix',      scope: 'sidebar',      title: 'Active nav item — neutral fg, surface-active tone',
    summary: '.ds-link.active and .nav-item.active now use background: var(--surface-active) + color: var(--fg) + font-weight 600. The ember-coloured text was distracting; the existing left rail + bold + surface-active tone are enough to mark the current page. Both selectors stay in sync.' },
  { version: 'v1.8.0', date: '2026-05-17', type: 'fix',      scope: 'foundations',  title: 'Spacing scale — column gap + bar room',
    summary: 'Bar column 80px → 110px (so the 96px max bar stops touching the description), grid gap 16 → 24, paddingInlineStart: 8 on description cell. Each row of the spacing table now has breathing room between the bar end and the usage text.' },
  { version: 'v1.8.0', date: '2026-05-17', type: 'docs',     scope: 'core',         title: 'Gap analysis report — eidos-design-system/gap-analysis.html',
    summary: 'Long-form audit of the DS in 5 categories (token discipline, primitives, page structure, copywriting, component composition). 17 findings prioritised crit / high / med / low / ok with file references and recommendations. Findings TKN-01, TKN-02, TKN-03, TKN-04, CMP-03, PRI-03 all addressed in this version; the rest are scheduled.' },
  { version: 'v1.8.0', date: '2026-05-17', type: 'fix',      scope: 'core',         title: 'Version badge synced to v1.8.0 in sidebar + topbar',
    summary: 'Sidebar sub-text ("Design System v1.8.0") and topbar pill ("v1.8.0 · Stable") updated in shell.jsx — they always stay in sync.' },

  // ─── v1.7.2 — Examples scroll fix (2026-05-17) ───────────────────
  { version: 'v1.7.2', date: '2026-05-17', type: 'fix',      scope: 'examples',     title: 'Standalone example pages can now scroll',
    summary: 'Root cause: ds.css and tokens.css set html/body { overflow: hidden !important; height: 100% !important } — intentional for the DS docs shell (which delegates scroll to #ds-root and lets each pane scroll internally), but those rules also applied to example pages (which load the same stylesheets but use .fp-app, not #ds-root). The !important made the body unscrollable, so every example page was clamped at viewport height regardless of content. Fix: scoped the no-scroll rules to body:has(#ds-root) / html:has(#ds-root) (and the matching rule in tokens.css for #root). Docs pages keep the locked-shell behaviour (rail + topbar fixed, panes scroll within #ds-root); example pages now scroll natively at the window — topbar stays sticky, content slides as expected. Validated headless on all 17 examples + 3 docs pages: 8/8 scroll correctly, docs shells unaffected.' },
  { version: 'v1.7.2', date: '2026-05-17', type: 'fix',      scope: 'core',         title: 'Version badge synced to v1.7.2 in sidebar + topbar',
    summary: 'Both display locations updated in lockstep per the saved sync rule.' },

  // ─── v1.7.1 — Pattern texture fixes (2026-05-17) ─────────────────
  { version: 'v1.7.1', date: '2026-05-17', type: 'fix',      scope: 'patterns',     title: 'Mesh gradient + dot grid + linear grid backgrounds now render inside .pat-demo',
    summary: 'Root cause: the docs-page demo helper .pat-demo declared background: var(--surface) (shorthand). CSS shorthand resets every background-* longhand including background-image, so any pattern class layered on top (.pat-mesh, .pat-dot-grid, .pat-linear-grid set their texture via background-image) had its texture wiped. .pat-demo now uses the background-color longhand — pattern textures coexist cleanly when composed.' },
  { version: 'v1.7.1', date: '2026-05-17', type: 'fix',      scope: 'patterns',     title: 'Noise grain visibility on dark theme',
    summary: 'mix-blend-mode: overlay over a near-black surface produced almost zero visible noise. Switched dark theme to mix-blend-mode: screen with a brighter feColorMatrix alpha (0.32) and a coarser turbulence baseFrequency (0.85 → 0.72, 2 → 3 octaves). is-subtle / default / is-strong opacity scale now reads as 0.45 / 0.85 / 1.0 in dark and 0.18 / 0.32 / 0.5 in light. Light theme keeps multiply blend with a dedicated dark-noise SVG so the texture lands the right way in both themes.' },
  { version: 'v1.7.1', date: '2026-05-17', type: 'fix',      scope: 'core',         title: 'Version badge synced to v1.7.1 in both sidebar + topbar',
    summary: 'sidebar sub-text and topbar pill bumped together — they always stay in sync per the saved feedback rule.' },

  // ─── v1.7.0 — Patterns reframed as visual effects (2026-05-17) ─────
  { version: 'v1.7.0', date: '2026-05-17', type: 'breaking', scope: 'patterns',     title: 'Patterns group reframed — visual effects only',
    summary: 'Patterns used to contain a mix of page-level shells (Dashboard, Detail, Catalog, Wizard, Console-split), section compositions (Hero, Page headers) and overlay UI (Sidesheet). That mix made the group hard to reason about. Patterns is now exclusively visual decoration: backgrounds, glows, textures. 8 new utility patterns landed (Dot grid, Linear grid, Mesh gradient, Conic orb, Radial spotlight, Noise grain, Ember glow, Gradient border) — each ships a CSS utility class and a docs page with variants + Do / Don\'t.' },
  { version: 'v1.7.0', date: '2026-05-17', type: 'breaking', scope: 'elements',     title: 'Hero and Page headers moved from Patterns → Elements',
    summary: 'These were always section-level compositions (Card + Pill + Avatar + …), not page-level shells. They now live alongside MetricCard / ServiceCard / AgentCard as recipes assembled from existing primitives. Slugs renamed to el-hero and el-page-headers; nav-config registers them under Elements.' },
  { version: 'v1.7.0', date: '2026-05-17', type: 'breaking', scope: 'sidesheet',    title: 'Sidesheet moved from Patterns → Components',
    summary: 'Sidesheet is an overlay primitive — same family as Drawer / Modal / Popover. Now lives under Components → Overlays & Dialogs. Slug stays sidesheet; only the nav location and the file path changed.' },
  { version: 'v1.7.0', date: '2026-05-17', type: 'breaking', scope: 'patterns',     title: 'Page-level shells removed — see Examples gallery',
    summary: 'Dashboard shell, Detail shell, Catalog shell, Wizard, Console split — the five page-level shells that used to live in Patterns — are gone. Their job (showing how to assemble a full Eidos product page) is owned by the Examples gallery: DORA Dashboard covers the dashboard shell, Service Detail / Catalog cover the detail / catalog shells, and the two new examples below cover Wizard + Console split.' },
  { version: 'v1.7.0', date: '2026-05-17', type: 'feat',     scope: 'examples',     title: 'Service Scaffold — new polished example',
    summary: 'A multi-step scaffold wizard: choose a template (T1 typescript-api gold standard, T2 python-worker, etc.), name the repo + pick a tribe + visibility, configure pipeline shape + ring strategy, set SLO target + dashboards / on-call provisioning, then review the generated artifacts and ship. Composes Pipeline (stepper), Banner, OwnerPill, StatusDot, in-group inputs — zero per-page CSS.' },
  { version: 'v1.7.0', date: '2026-05-17', type: 'feat',     scope: 'examples',     title: 'Pipeline Console — new polished example',
    summary: 'Operator console with split layout: recent runs on the left (status dot + step strip + author + relative time), live log + step pipeline + run detail on the right. Tabs for Logs / Artifacts / Tests / Env. Filter chips for log levels. Composes LogViewer, Pipeline (chevron), StatusDot, CopyChip, OwnerPill, RelativeTime, Banner.' },
  { version: 'v1.7.0', date: '2026-05-17', type: 'feat',     scope: 'patterns',     title: '8 visual pattern utilities + docs pages',
    summary: 'Dot grid (graph-paper dots for heroes), Linear grid (graph-paper lines for workflow canvases), Mesh gradient (organic blend for AI surfaces — ember+ice / cool / warm), Conic orb (blurred decorative sphere, ember or ice, optional spin), Radial spotlight (vignette to focus eye), Noise grain (SVG turbulence overlay, theme-inverted blend mode), Ember glow (the active-step halo, now a public utility), Gradient border (premium / AI flag, mask-composite, optional conic spin).' },
  { version: 'v1.7.0', date: '2026-05-17', type: 'fix',      scope: 'core',         title: 'Sidebar version badge bumped to v1.7.0',
    summary: 'Both the sidebar sub-text ("Design System v1.7.0") and the topbar pill ("v1.7.0 · Stable") updated in shell.jsx — they always stay in sync.' },

  // ─── v1.6.1 — Cache-busting fix (2026-05-16) ──────────────────
  { version: 'v1.6.1', date: '2026-05-16', type: 'fix',      scope: 'core',         title: 'Page-specific JSX now respects cache version',
    summary: '43 HTML shells were referencing their page JSX (e.g. <script src="assets/js/pages/resources/changelog.jsx">) without a ?v= suffix. The browser kept serving the stale cached file even after we bumped the global cache version, so changelog entries, page rebuilds, and Do/Don\'t fixes appeared "not deployed". All 43 shells now carry ?v=20260516h on every page script — and the global cache bumped to 20260516h. Going forward, sub-agent templates that clone _template.html must keep the ?v= placeholder.' },

  // ─── v1.6.0 — Targeted regressions + clean-ups (2026-05-16) ──
  { version: 'v1.6.0', date: '2026-05-16', type: 'fix',      scope: 'core',         title: 'Sidebar external links now navigate inside iframe previews',
    summary: 'In sandboxed iframe previews (OD\'s preview pane), the target="_blank" attribute silently fails when allow-popups is missing — every "Open in new tab" click looked like nothing happened. NavLink now also calls window.open(); if that returns null we fall back to navigating window.top so the example always opens.' },
  { version: 'v1.6.0', date: '2026-05-16', type: 'fix',      scope: 'banner',       title: 'Banner reverted to flat AlertBar style',
    summary: 'Dropped the 28 px icon tile, the size sm/md/lg variants, and the gradient-tinted custom tone. Banner now matches the original Alert primitive: inline icon, baseline-aligned title + message, ghost CTA on the right. Tones use the same --*-soft tokens as Alert — visual vocabulary stays unified between the two.' },
  { version: 'v1.6.0', date: '2026-05-16', type: 'fix',      scope: 'core',         title: 'Sidebar search spans the full sidebar width',
    summary: 'The search trigger sat at 10 px horizontal margin while nav links sat at the sidenav\'s 12 px padding — visually shorter than the links. Margin dropped to 0 with width:100% and box-sizing:border-box so it aligns to the same horizontal extent as every nav row.' },
  { version: 'v1.6.0', date: '2026-05-16', type: 'fix',      scope: 'filter-panel', title: 'FilterPanel rows now use Eidos\'s .fc-* form-control chrome',
    summary: 'Each option row replaced its naked browser checkbox / radio with .fc-check-box + .fc-check-icon (or .fc-radio-box + .fc-radio-dot). The actual <input> stays as the accessible target — visible chrome matches the Checkbox / Radio components.' },
  { version: 'v1.6.0', date: '2026-05-16', type: 'breaking', scope: 'pipeline',     title: 'Pipeline variants gantt / ring / vertical removed',
    summary: 'Pipeline is now a strictly horizontal primitive with two variants: stepper and chevron. Top-down sequences belong to Timeline. Stage-progress visuals (rings) belong to RingBar / ScoreGauge. The Gantt-mini layout never earned its slot.' },
  { version: 'v1.6.0', date: '2026-05-16', type: 'breaking', scope: 'timeline',     title: 'Timeline horizontal variant removed',
    summary: 'Timeline is now vertical-only — for left-to-right step trackers use <Pipeline variant="stepper"/> or "chevron". The previous wizard tracker has been folded into Pipeline\'s stepper / chevron variants.' },
  { version: 'v1.6.0', date: '2026-05-16', type: 'breaking', scope: 'elements',     title: 'Severity pill, Health badge, and Stat element pages removed',
    summary: 'These were thin wrappers over an existing .pill class — they did not earn a separate recipe page. Use <Pill className="severity-p0/p1/p2/p3"/> for incident severity and <Pill className="health-up/degraded/down/unknown"/> for service health directly. Stat\'s job is covered by MetricCard.' },
  { version: 'v1.6.0', date: '2026-05-16', type: 'fix',      scope: 'metric-card',  title: 'MetricCard labels now align across a KPI row',
    summary: 'When one card\'s label wrapped to two lines ("CHANGE FAILURE") and a neighbour\'s did not ("MTTR"), the big numbers landed at different vertical positions. .mc-head now has min-height = 2 lines so every header occupies the same space — values line up no matter the wrap.' },
  { version: 'v1.6.0', date: '2026-05-16', type: 'fix',      scope: 'agent-card',   title: 'AgentCard layout — uniform height + summary clamp',
    summary: 'Cards in auto-fill grids now stretch to row height. Summary clamps at 3 lines via -webkit-line-clamp so card heights stay even regardless of summary length. .ac-foot uses margin-top:auto to pin metrics to the bottom edge. Padding bumped from 20px → 22px; gap 16 → 18; avatar 36 → 40.' },
  { version: 'v1.6.0', date: '2026-05-16', type: 'fix',      scope: 'charts',       title: 'Chart titles + legend titles + heatmap popover legibility',
    summary: 'fc-title bumped 14 → 15 px, fc-subtitle 12 → 13 px + weight 500 + brighter --fg-muted, fc-meta still mono but on --fg-muted (was --fg-faint). Recharts legend-item-text 13 → 13.5 px. Heatmap popover title 13 → 14 px / letter-spacing tightened. Cartesian axis ticks 11.5 → 12 px / weight 500. Polar ticks 12 → 12.5 px / weight 500 / --fg-muted → --fg.' },
  { version: 'v1.6.0', date: '2026-05-16', type: 'fix',      scope: 'charts',       title: 'Do / Don\'t live demos rendered empty',
    summary: '.dd-card .body is a flex-center wrapper, so block-level chart children collapsed to 0 width — Recharts ResponsiveContainer reported 0×140 and emitted nothing. Added explicit width:100% on .eidos-chart / .pipeline / .timeline / .ring-bar inside Do / Don\'t bodies so all live demos render at full container width.' },

  // ─── v1.5.0 — Phase 3 polish round + Examples in sidebar (2026-05-16) ──
  { version: 'v1.5.0', date: '2026-05-16', type: 'feat',     scope: 'core',       title: 'Examples group in the sidebar',
    summary: 'All 15 standalone IDP examples (AI Insights, Agent Chat, Service Catalog, DORA Dashboard, Ring Deployment, etc.) now have an entry in the docs sidebar between Patterns and Resources. Each entry is marked external — clicking opens the product page in a new tab so engineers stay anchored to the docs.' },
  { version: 'v1.5.0', date: '2026-05-16', type: 'breaking', scope: 'workflow-canvas', title: 'WorkflowCanvas removed',
    summary: 'The hand-rolled ReactFlow-style DAG never reached the polish bar we set for it — edges crossed nodes, kind colours fought each other, and the visual was hard to scan. Removed the JSX block, CSS, page, and example. If/when we ship a DAG primitive it will start from a clean ReactFlow integration.' },
  { version: 'v1.5.0', date: '2026-05-16', type: 'feat',     scope: 'pipeline',   title: 'Pipeline rebuilt from scratch',
    summary: 'Stepper now uses a 28 px circular pin with status icon inside, joined by a dashed rail at the pin centerline (predecessor-tinted). Chevron is a true nested-arrow shape via CSS clip-path with a 2 px gap between cells — no more overlapping borders. Vertical and Ring variants got bigger pins (22 px / 52 px ring) for legibility. Current step pulses with an ember halo across every variant.' },
  { version: 'v1.5.0', date: '2026-05-16', type: 'fix',      scope: 'ring-bar',   title: 'Ring bar legibility + concentric variant retired',
    summary: 'Linear cells were too tight — audience text used --fg-faint which clipped to grey-on-grey. Rewrote: 14 px / 600 label, 12.5 px / muted audience (legible in both themes), tabular percent on the right, status-tinted track, grid auto-fit layout. Concentric variant removed — it read as a bullseye rather than a journey; ring rollouts are inherently left-to-right.' },
  { version: 'v1.5.0', date: '2026-05-16', type: 'feat',     scope: 'timeline',   title: 'Timeline — active step pulses ember',
    summary: 'Items marked current: true now render with an ember halo pulse around the pin + ember-tinted body card. Done items go quiet green. The horizontal variant matches. New tl-halo animation tl-halo-pulse 1.8s.' },
  { version: 'v1.5.0', date: '2026-05-16', type: 'fix',      scope: 'charts',     title: 'Chart legend + axis text legibility',
    summary: 'Recharts default legend at 12px / --fg-muted was hard to read. Bumped to 13 px / --fg / 500 with 18px item gap. Cartesian axis ticks went from 11px / --fg-faint to 11.5px / --fg-muted. Polar (radar) ticks went to 12px / --fg-muted / 500. Polar grid softened to 0.55 opacity so data shapes pop.' },
  { version: 'v1.5.0', date: '2026-05-16', type: 'fix',      scope: 'chart-sankey', title: 'Sankey rendered empty — fixed the link renderer',
    summary: 'The previous EidosLink read props.d, but Recharts Sankey passes sourceX/targetX/sourceY/targetY/sourceControlX/targetControlX + linkWidth and expects the renderer to build the path. Rewrote EidosLink to construct the cubic bezier; ribbons now appear with palette-indexed colours and stroke-opacity 0.28 → 0.6 on hover.' },
  { version: 'v1.5.0', date: '2026-05-16', type: 'fix',      scope: 'chart-radar', title: 'Radar polygons softer, axis text legible',
    summary: 'Stroke 2 → 1.25, fill opacity 0.25 → 0.18, polar grid radial lines off, axis labels promoted to 12 px / --fg / 500 via a shared angleTick style. Dots stroked in --surface so they pop without breaking the polygon shape. Comparison radar (two series) reads clearly now.' },
  { version: 'v1.5.0', date: '2026-05-16', type: 'feat',     scope: 'chart-heatmap', title: 'Heatmap cell hover popover (AI Label style)',
    summary: 'Hovering any calendar or matrix cell now opens a Eidos-styled popover (lifted from AILabelWithPopover) with the cell title, intensity label (Low/Moderate/High), exact score and bucket. Cell border tints to ember during hover for a clear hit zone. New .heat-pop CSS class.' },
  { version: 'v1.5.0', date: '2026-05-16', type: 'feat',     scope: 'chart-gauge', title: 'Gauge page rewritten from scratch (plain SVG)',
    summary: 'The previous PieChart-based gauge mis-centered inside ResponsiveContainer (cx/cy percentages did not resolve until after first layout). Replaced with a 30-line SVG primitive: three variants (semi 180° / three-q 270° / full 360°), explicit polar math, centered readout with tabular-nums. Variants include a Change Risk Score recipe (green/amber/red tinted by value).' },
  { version: 'v1.5.0', date: '2026-05-16', type: 'docs',     scope: 'charts',     title: 'Do / Don\'t notes strengthened',
    summary: 'Line, Area, Bar, Histogram, Pie, Radial, Composed — every chart\'s "Do / Don\'t" notes now spell out the failure mode + the recommended alternative (use ReferenceLine, switch to horizontal bar, use ComposedChart with two yAxisIds, etc.) rather than a one-line truism.' },

  // ─── v1.4.0 — Phase 5 (Patterns) + Phase 6 (Examples) + Chart polish (2026-05-16) ──
  { version: 'v1.4.0', date: '2026-05-16', type: 'feat',     scope: 'examples',   title: 'IDP Examples gallery — 16 standalone product pages',
    summary: 'A new section that lives outside the docs shell and simulates the Eidos IDP product. 16 pages: AI Insights (home), Agent Chat (right drawer with tool calls + citations), Service Catalog, Service Detail, DORA Dashboard, Pipeline View, Ring Deployment, Feature Flags, Quality Gates, Score Cards, Agent Catalog, MCP Detail, Workflow Canvas, Incident Room, Cloud Inventory, Templates. Each page is built only from existing primitives — zero per-page CSS.' },
  { version: 'v1.4.0', date: '2026-05-16', type: 'feat',     scope: 'examples',   title: 'AI Insights — Eidos agent home',
    summary: 'Landing page of the Eidos IDP. Hero strip with top 3 ranked findings (drift, risk, cost), 4 KPI cards, agent-ranked insights feed, today\'s priorities sidebar, tribe pulse strip, weekly digest. Inspired by Linear AI / Github / Backstage homepage patterns.' },
  { version: 'v1.4.0', date: '2026-05-16', type: 'feat',     scope: 'examples',   title: 'Agent Chat — ChatGPT-in-the-platform drawer',
    summary: 'Service detail page with the Eidos agent in a 480px right drawer. Demonstrates user turns, agent turns with citations, thinking blocks, tool calls (observability.read, eidos.openPR), and inline PR drafts with Change Risk Score. Inspired by Cursor / Copilot Chat / Linear AI.' },
  { version: 'v1.4.0', date: '2026-05-16', type: 'feat',     scope: 'patterns',   title: '5 pattern shells',
    summary: 'dashboard-shell · detail-shell · catalog-shell · wizard · console-split — composable layout templates that demonstrate how to wire primitives together for the most common page types in an IDP. All five live under Patterns.' },
  { version: 'v1.4.0', date: '2026-05-16', type: 'fix',      scope: 'charts',     title: 'Hover / highlight colours theme-aware',
    summary: 'Recharts ships default cursor rgb(204,204,204) and white active dots — neither reads correctly in either Eidos theme. Added scoped CSS overrides for .recharts-tooltip-cursor, .recharts-active-dot, .recharts-active-bar, .recharts-pie-sector:hover, .recharts-sankey-link:hover, and the entire .recharts-brush component family. Dark and light mode now show the same legibility.' },
  { version: 'v1.4.0', date: '2026-05-16', type: 'feat',     scope: 'core',       title: 'Example shell + product chrome',
    summary: 'New example-shell.css and example-shell.jsx assets simulate the Eidos IDP product: 56 px primary rail with 13 destinations, sticky topbar with breadcrumbs + ⌘K + agent button + user avatar, grid helpers (fp-grid-2/3/4/auto/2x1), KPI tile (fp-kpi), section header, drawer chrome (fp-drawer). Pages compose from this shell.' },

  // ─── v1.3.0 — Phase 3 rework + Charts / Elements (2026-05-16) ────────────
  { version: 'v1.3.0', date: '2026-05-16', type: 'feat',     scope: 'charts',     title: 'Charts group with 11 chart types',
    summary: 'Recharts-powered, themed with Eidos tokens. Bar, line, area, histogram, pie, gauge, composed, radar, radial, sankey, heatmap. Each page documents 2–4 variants and a real IDP-shaped dataset. New <EidosChart>, <EidosTooltipContent>, useChartColors helpers in charts.jsx.' },
  { version: 'v1.3.0', date: '2026-05-16', type: 'feat',     scope: 'elements',   title: 'Elements group — IDP recipes',
    summary: 'New top-level group dedicated to compositions of existing primitives. 8 pages: severity-pill, health-badge, metric-card, score-gauge, service-card, agent-card, stat — plus an overview landing. Pages emphasise that these are recipes, not new components.' },
  { version: 'v1.3.0', date: '2026-05-16', type: 'feat',     scope: 'banner',     title: 'Banner (replaces Alert bar)',
    summary: 'Renamed from alert-bar. Adds custom-bg / fg / accent for branded announcements, sm/md/lg sizes, and a dedicated CTA slot. Old slug retired.' },
  { version: 'v1.3.0', date: '2026-05-16', type: 'feat',     scope: 'pipeline',   title: 'Pipeline — five variants',
    summary: 'stepper (default) · chevron (chained arrows) · vertical · gantt-mini · ring stages. One step model drives every variant.' },
  { version: 'v1.3.0', date: '2026-05-16', type: 'feat',     scope: 'ring-bar',   title: 'Ring bar — concentric variant + popover',
    summary: 'Adds variant="concentric" (one ring per cohort in a single SVG) and popoverFor render-prop on linear cells for inline detail cards.' },
  { version: 'v1.3.0', date: '2026-05-16', type: 'feat',     scope: 'score-gauge',title: 'Score gauge — automotive speedo',
    summary: 'Rebuilt as a 180° sweep with gradient, tick marks, optional segment labels, and a centred readout. Variants: speedo (0–1000 default), compact ring, linear bar. Designed for Change Risk Score, Reliability Index, Service Health Score.' },
  { version: 'v1.3.0', date: '2026-05-16', type: 'feat',     scope: 'tree-view',  title: 'Tree view — trees.software polish',
    summary: 'Explicit indent guides, chevron toggle with rotation, folder / file glyphs, optional meta + badge per row, ember selection accent. Click on any row toggles its children.' },
  { version: 'v1.3.0', date: '2026-05-16', type: 'feat',     scope: 'workflow-canvas', title: 'Workflow canvas — ReactFlow style',
    summary: 'Rounded nodes with handles, curved bezier edges with arrow markers, optional dotted background, 6 node kinds (trigger / action / decision / agent / wait / end) and 4 status tones.' },
  { version: 'v1.3.0', date: '2026-05-16', type: 'feat',     scope: 'log-viewer', title: 'Log viewer — filterable variant',
    summary: 'Adds a toolbar with severity chips + inline search. New "expanded" variant exposes the timestamp column. Auto-scroll on streaming logs (follow prop).' },
  { version: 'v1.3.0', date: '2026-05-16', type: 'feat',     scope: 'diff-viewer',title: 'Diff viewer — split + unified',
    summary: 'Side-by-side diff with per-side line numbers, paired deletions/additions, per-file header with +N / −M counts. wrap prop for long lines.' },
  { version: 'v1.3.0', date: '2026-05-16', type: 'feat',     scope: 'trend',      title: 'Trend — 4 variants',
    summary: 'arrow (default ↑ ↓ —), triangle (▲ ▼ ◆ for dense tables), badge (pill chrome for feature rows), bar (delta bar neighbour to a sparkline).' },
  { version: 'v1.3.0', date: '2026-05-16', type: 'feat',     scope: 'relative-time', title: 'Relative time — Eidos tooltip',
    summary: 'Opt-in tooltip prop renders the full absolute datetime (with seconds) inside the design system .tt tooltip. Native title= fallback when tooltip is false.' },
  { version: 'v1.3.0', date: '2026-05-16', type: 'feat',     scope: 'timeline',   title: 'Timeline — horizontal variant',
    summary: 'Adds variant="horizontal" — a step tracker for wizards and deploy progress with rail + pin + line connectors.' },
  { version: 'v1.3.0', date: '2026-05-16', type: 'feat',     scope: 'data-table', title: 'Data table — sortable, sticky, dense + IDP examples',
    summary: 'New props: sort / onSort, sticky, dense, footer. Three new examples: service health row (sparkline + Trend), incident inventory (SeverityPill + RelativeTime + CopyChip), sortable+sticky inside a scroll container.' },
  { version: 'v1.3.0', date: '2026-05-16', type: 'feat',     scope: 'service-card', title: 'Service card — clean + detailed variants',
    summary: 'Roomier spacing, sparkline header label, two layouts: variant="clean" (catalog grid) and variant="detailed" (with footer KPIs).' },
  { version: 'v1.3.0', date: '2026-05-16', type: 'feat',     scope: 'agent-card', title: 'Agent card — breathable layout',
    summary: 'New 36 px avatar tile, multi-line summary slot, capabilities chip row, KPI footer (runs/24h, success, last run).' },
  { version: 'v1.3.0', date: '2026-05-16', type: 'feat',     scope: 'metric-card',title: 'Metric card — sm/md/lg sizes + tones',
    summary: 'Renders value with tabular-nums (no count-up). Adds sm/md/lg sizes, tone strip (success/warning/danger/ember).' },
  { version: 'v1.3.0', date: '2026-05-16', type: 'feat',     scope: 'badges',     title: 'Badge page rewritten',
    summary: 'KBD and Avatar examples removed (those live on their own pages). New examples: numeric counts, version tags, in-sidebar rollups, push-end modifier, contract vs. Pill.' },
  { version: 'v1.3.0', date: '2026-05-16', type: 'feat',     scope: 'kbd',        title: 'Kbd page — KbdRow section',
    summary: 'Folded the standalone kbd-row page into Kbd. Shows the row composition (label + meta + chord) used in menus, command palettes, cheat-sheets.' },
  { version: 'v1.3.0', date: '2026-05-16', type: 'feat',     scope: 'avatars',    title: 'Avatar page — Owner pill section',
    summary: 'Folded the standalone owner-pill page into Avatar. Shows the Avatar + name + role composition used in catalogs, incident commanders, PR reviewer rows.' },
  { version: 'v1.3.0', date: '2026-05-16', type: 'breaking', scope: 'core',       title: 'Re-shuffled Components subgroup',
    summary: 'Severity-pill, health-badge, metric-card, score-gauge, service-card, agent-card, stat moved from Components/IDP Blocks to the new Elements group. Heatmap moved to Charts. Alert bar renamed to Banner. Kbd-row and Owner-pill folded into Kbd and Avatar respectively. URLs of all moved pages changed.' },
  { version: 'v1.3.0', date: '2026-05-16', type: 'tokens',   scope: 'core',       title: 'Recharts UMD pinned + charts.jsx wrapper',
    summary: 'recharts@2.12.7 and prop-types@15.8.1 added as pinned UMD dependencies in _template.html. New assets/js/core/charts.jsx wraps Recharts with Eidos tokens (viz palette, axis font, tooltip surface, container chrome).' },

  // ─── v1.2.0 — Phase 1 + Phase 2 + Phase 4 (2026-05-15) ──────────────────
  { version: 'v1.2.0', date: '2026-05-15', type: 'tokens',   scope: 'core',       title: 'IDP semantic palettes',
    summary: '23 new tokens: data viz (cat-1..12, seq-low/mid/high, div-neg/zero/pos), severity (P0..P3), status (5-state), health (4-state), risk (4-state), breakpoints (--bp-sm..2xl), tabular nums + opacity scales. Mirror in [data-mode="light"].' },
  { version: 'v1.2.0', date: '2026-05-15', type: 'feat',     scope: 'foundation', title: 'Severity & state foundation page',
    summary: 'New page documenting the four IDP semantic families (severity / status / health / risk) with a decision matrix and a one-row composition showing all four side-by-side.' },
  { version: 'v1.2.0', date: '2026-05-15', type: 'feat',     scope: 'core',       title: '10 new atoms (Phase 2)',
    summary: 'StatusDot, Trend, HealthBadge, SeverityPill, KbdRow, CountUp, CopyChip, RelativeTime, OwnerPill, TierBadge — every one composes existing primitives (Pill / Avatar / Sparkline) and lives in atoms.jsx.' },
  { version: 'v1.2.0', date: '2026-05-15', type: 'feat',     scope: 'iconography',title: '24 IDP-specific icons',
    summary: 'DevOps (deploy, rollback, pipeline, merge, commit, tag, gate, ring), cloud (fn, queue, region, key), agent/AI/MCP (agent, mcpServer, toolCall, prompt, vector), governance (incident, score, compliance, auditLog, runbook, slo, flag). Foundation page reorganised by domain.' },
  { version: 'v1.2.0', date: '2026-05-15', type: 'feat',     scope: 'core',       title: '"New" / "Updated" badges on nav links',
    summary: 'Sidebar links can declare badge: "new" | "updated" | "beta" in nav-config and render an inline pill. Drives the visual signal for everything shipping under v1.2 and v1.3.' },
  { version: 'v1.2.0', date: '2026-05-15', type: 'fix',      scope: 'core',       title: 'DEF-01..09 from the gap analysis',
    summary: 'Message extracted to atoms (deduped 226 lines across 4 AI pages). Empty primitive shared. Density modifier (data-density). Pill/Badge/Chip contract documented. Status colours migrated off hardcodes. RTL audit. Live-region docs. prefers-color-scheme respected on first paint.' },

  // v1.1.0 — current sprint, world-class hardening pass
  { version: 'v1.1.0', date: '2026-05-14', type: 'tokens',   scope: 'core',        title: 'Foundation tokens declared',
    summary: '--space-* (4 px ladder), --radius-*, --text-*, --z-*, --prose-*, --ai-*, --ease-* / --dur-* now exist as real CSS variables. Spacing & Radius foundation page is no longer aspirational.' },
  { version: 'v1.1.0', date: '2026-05-14', type: 'feat',     scope: 'shell',       title: '⌘K command palette',
    summary: 'Global ⌘K (Ctrl+K on Windows) opens a fuzzy-search overlay across every page in the nav. ↑↓ to navigate, Enter to open, Esc to close.' },
  { version: 'v1.1.0', date: '2026-05-14', type: 'feat',     scope: 'core',        title: 'Auto-injected Installation block',
    summary: '<Section> now renders <ComponentInstall slug={…}/> automatically for any page in the Components or AI groups — install boilerplate lives in one place instead of being copy-pasted across 60+ pages. Opt-out with autoInstall={false}.' },
  { version: 'v1.1.0', date: '2026-05-14', type: 'feat',     scope: 'ai-citations',title: 'Citations component',
    summary: 'Inline numbered chips + sources panel for assistant responses with attributable sources.' },
  { version: 'v1.1.0', date: '2026-05-14', type: 'feat',     scope: 'ai-errors',   title: 'AI error states',
    summary: 'Model-down, rate-limited, refusal, context-overflow, network-timeout, partial-failure — all six surfaces with copy + recovery CTAs.' },
  { version: 'v1.1.0', date: '2026-05-14', type: 'feat',     scope: 'ai-history',  title: 'Conversation history sidebar',
    summary: 'Date-grouped thread list with search, starred items, rename / delete on hover.' },
  { version: 'v1.1.0', date: '2026-05-14', type: 'a11y',     scope: 'a11y',        title: 'Accessibility reference rebuilt',
    summary: 'WCAG 2.2 matrix, component × ARIA grid, real measured contrast pairs, keyboard map, reduced-motion contract, audit log.' },
  { version: 'v1.1.0', date: '2026-05-14', type: 'feat',     scope: 'patterns',    title: 'Patterns upgraded to Components depth',
    summary: 'Hero, Page Headers, Sidesheet now ship Anatomy + Decision matrix + Do/Don’t + RTL — same rigor as Buttons.' },
  { version: 'v1.1.0', date: '2026-05-14', type: 'docs',     scope: 'core',        title: 'Pinned React/Babel runtime documented',
    summary: 'Installation page now lists the exact versions and SRI hashes used by every page shell, plus the bump-version.sh workflow.' },
  { version: 'v1.1.0', date: '2026-05-14', type: 'fix',      scope: 'core',        title: 'No more global !important on focus',
    summary: 'The global :where(input:focus) rule is now specificity-0 — component-level overrides win on cascade rules instead of fighting !important.' },
  { version: 'v1.1.0', date: '2026-05-14', type: 'fix',      scope: 'overview',    title: 'Stats no longer invented',
    summary: 'Hero stats (Components / Patterns / Tokens) are now computed from the live nav config + token declarations.' },

  // v1.0.x — released
  { version: 'v1.0.0', date: '2026-05-01', type: 'feat',     scope: 'core',        title: 'First stable release',
    summary: 'Ember as the single accent. Tailwind v4 @theme preset. Geist + Geist Mono. Six-color surface palette.' },
  { version: 'v0.9.0', date: '2026-03-12', type: 'feat',     scope: 'components',  title: 'Coverage parity with product',
    summary: 'All 60+ components in the production catalog (catalog, deploys, GMUDs, runbooks) shipped with usage docs and Anatomy.' },
  { version: 'v0.8.0', date: '2026-02-04', type: 'feat',     scope: 'foundation',  title: 'Light theme parity',
    summary: 'Light mode redrawn from the ground up — tinted (not pure-black) shadows, dedicated input/toggle treatment, separate code-block palette.' },
  { version: 'v0.8.0', date: '2026-02-04', type: 'tokens',   scope: 'foundation',  title: 'Hairline-only borders',
    summary: '--border / --border-strong / --border-stronger replaced ad-hoc 1px rgba calls. The decorative ember pulse is retired from non-live states.' },
  { version: 'v0.7.0', date: '2026-01-15', type: 'tokens',   scope: 'foundation',  title: 'Type scale rewritten on Geist',
    summary: '11 px / 0.08 em tracking mono labels. Display sizes anchored at 28 / 36 / 56 / 72.' },
  { version: 'v0.6.0', date: '2025-12-08', type: 'feat',     scope: 'rtl',         title: 'RTL coverage bootstrapped',
    summary: 'Logical properties (inset-inline-*, padding-inline-*, margin-inline-*) replaced physical ones across the system. Carousel, Switch, Slider mirror correctly.' },
  { version: 'v0.5.0', date: '2025-11-04', type: 'feat',     scope: 'core',        title: 'Project structure split',
    summary: 'Each page is its own HTML file with a base href + IIFE-registered component. Single-source nav config in nav-config.js.' },
];

export default function Changelog() {
  return (
    <ChangelogView
      entries={CHANGELOG}
      num="23"
      title="Changelog"
      desc="Every meaningful change to Eidos — searchable, filterable, scoped per component."
      dsName="Eidos Design System"
    />
  );
}
